const fs=require('fs'),vm=require('vm'),assert=require('assert');const root=__dirname+'/../source/';
vm.runInThisContext(['geometry.js','wall-shadow2.js','operation-counts.js'].map(f=>fs.readFileSync(root+f,'utf8')).join('\n')+String.raw`
const check=(ok,message)=>{if(!ok)throw Error(message);},eq=(a,b,message)=>check(JSON.stringify(a)===JSON.stringify(b),message),withoutMS=x=>JSON.parse(JSON.stringify(x,(k,v)=>k==='ms'?undefined:v));
const functionsBefore=[clip,val3,rayHit,rayTri3,intersectFast,rayBox,locate2,clipSegment2,expandVector2,rasterCube];
const square=[[0,0],[2,0],[2,2],[0,2]],h={n:[1,0],d:1};
let measured=measureSolverWork(()=>clip3(square,h));eq(measured.value,clip3(square,h),'Clip output changed');check(measured.work.polygonClips===1&&measured.work.halfPlaneTests===5&&measured.work.geometricTests===5,'Clip predicates counted twice or repeated closing vertex omitted');
measured=measureSolverWork(()=>clip([],()=>{throw Error('Empty callback invoked');}));check(measured.work.polygonClips===1&&measured.work.geometricTests===0,'Empty clip predicate accounting');
measured=measureSolverWork(()=>{val3(h,[0,0]);return clip3(square,h);});check(measured.work.halfPlaneTests===6,'Standalone signed plane omitted');
const edge=[[0,0],[1,0]],reject=[{n:[1,0],d:2},{n:[0,1],d:2}];measured=measureSolverWork(()=>clipSegment2(edge,reject));check(measured.value===null&&measured.work.halfPlaneTests===2&&measured.work.segmentClips===1,'Segment early rejection did not stop counting');
for(let i=0;i<100;i++){const a=[Math.sin(i)*8,Math.cos(i)*8],b=[Math.sin(i+.7)*8,Math.cos(i+.7)*8],planes=[{n:[1,0],d:1},{n:[0,1],d:-2}];eq(measureSolverWork(()=>clipSegment2([a,b],planes)).value,clipSegment2([a,b],planes),'Segment arithmetic/branches changed');}
try{measureSolverWork(()=>{clip3(square,h);throw Error('Deliberate solver failure');});throw Error('Expected failure');}catch(e){check(e.message==='Deliberate solver failure','Wrong failure');}
check(functionsBefore.every((f,i)=>f===[clip,val3,rayHit,rayTri3,intersectFast,rayBox,locate2,clipSegment2,expandVector2,rasterCube][i]),'Bindings not restored on throw');
try{measureSolverWork(()=>measureSolverWork(()=>1));throw Error('Expected nested failure');}catch(e){check(e.message.includes('cannot be nested'),'Nested guard failed');}
check(measureSolverWork(()=>1).work.geometricTests===0,'Nested exception leaked measurement state');
const scene=SCENES[0],q=[43,32];scene.mesh.index=makeBVH(scene.mesh.tris,2);
const located=measureSolverWork(()=>locate2(q,scene.mesh));check(located.work.pointBoxTests===located.value.ops.boxes&&located.work.sideTests===3*located.value.ops.triangles,'Point location predicate accounting');
const expansion=measureSolverWork(()=>expandVector2(q,scene));eq(withoutMS(expansion.value),withoutMS(expandVector2(q,scene)),'Instrumented expansion changed output');check(expansion.work.polygonClips===expansion.value.ops.clips,'Expansion clip pass count');
const subtraction=subtract2(q,scene),wall=wallSolverWork(subtraction),prep=wallPreparationWork(subtraction);check(wall.geometricTests===subtraction.stats.at(-1).vertexTests+subtraction.stats.at(-1).supportTests&&wall.polygonClips===subtraction.stats.at(-1).halfPlaneClips,'Wall solver uses display/preparation work');check(wallSolverWork(subtraction,0).geometricTests===0&&prep.geometricTests>0,'Wall preparation not separated');check(Math.abs(expansion.value.area-subtraction.area)<1e-6,'Compared outputs do not agree');
const attached=attachSolverWork(()=>subtract2(q,scene),'wall');eq(attached.work,wall,'Attached wall work differs');eq(attached.preparation,prep,'Attached preparation differs');check(attached.workBySnapshot.length===attached.snapshots.length&&attached.workBySnapshot[0].geometricTests===0,'Wall snapshot work');eq(sumSolverWork(wall,prep).geometricTests,wall.geometricTests+prep.geometricTests,'Work aggregation');eq(pointLocationWork(located.value.trace),located.work,'Locator trace work');
const ray=measureSolverWork(()=>sampleRay2(q,scene,8,false));check(ray.work.rayPrimitiveTests===8*sceneEdges(scene).length&&ray.work.geometricTests===ray.work.rayPrimitiveTests,'Brute force ray fixture');
scene.edgeIndex=makeBVH(sceneEdges(scene).map(e=>[e.a,e.b]),2);const indexed=measureSolverWork(()=>sampleRay2(q,scene,8,true));check(indexed.work.rayPrimitiveTests===indexed.value.stats.tests&&indexed.work.rayBoxTests===indexed.value.stats.boxes,'Indexed ray fixture');
const event=measureSolverWork(()=>visibility(q,scene));eq(event.value,visibility(q,scene),'Event-sector output changed');check(event.work.rayPrimitiveTests===event.value.sectors.length*(sceneEdges(scene).length+2),'Event-sector ray accounting');
const planarRaster=measureSolverWork(()=>rasterMap2(q,scene,4));check(planarRaster.work.rayPrimitiveTests===planarRaster.value.stats.tests,'Planar raster is LOS rather than depth raster');
const tris=[[[3,-1,-1],[3,1,-1],[3,0,1]]],prepared=prepare3(tris),rays3=measureSolverWork(()=>rayCube([0,0,0],prepared,2,false));check(rays3.work.rayPrimitiveTests===24&&rays3.work.geometricTests===24,'Cube ray fixture');
const raster=measureSolverWork(()=>rasterCube([0,0,0],tris,4));eq(withoutMS(raster.value),withoutMS(rasterCube([0,0,0],tris,4)),'Raster output changed');check(raster.work.rasterCoverageTests===raster.value.stats.pixelCandidates*3&&raster.work.rasterDepthTests===raster.value.stats.fragments&&raster.work.halfPlaneTests>0,'Raster coverage/depth/clipping accounting');
const terrain=inputTerrain(2,2),q3=[20,30,terrainZ(20,30)+4],air=terrainWithCeiling(terrain,q3,1),beam=measureSolverWork(()=>expand3(q3,air));eq(beam.value,expand3(q3,air),'3D beam output changed');check(beam.work.halfPlaneTests>0&&beam.work.polygonClips>0,'3D beam work omitted');
const patchTargets=surfacePatches(terrain.tris,32),surfaceRays=measureSolverWork(()=>sampleSurface(q3,prepare3(terrain.tris),patchTargets,true));check(surfaceRays.work.rayPrimitiveTests===surfaceRays.value.stats.tests&&surfaceRays.work.rayBoxTests===surfaceRays.value.stats.boxes,'Surface-target sample counting');
const cuts=measureSolverWork(()=>referenceSurface3(q3,terrain.tris));eq(withoutMS(cuts.value),withoutMS(referenceSurface3(q3,terrain.tris)),'Terrain subtraction changed output');check(cuts.work.halfPlaneTests>=cuts.value.stats.planeEvaluations,'Terrain broad-phase work omitted');
const urban=urbanModel(),urbanCut=measureSolverWork(()=>visibility3([18,31,28],urban.receivers,urban.objects));eq(urbanCut.value,visibility3([18,31,28],urban.receivers,urban.objects),'Urban cut changed output');check(urbanCut.work.halfPlaneTests>0,'Urban visibility omitted');
check(functionsBefore.every((f,i)=>f===[clip,val3,rayHit,rayTri3,intersectFast,rayBox,locate2,clipSegment2,expandVector2,rasterCube][i]),'Bindings not restored after successful solvers');
console.log(JSON.stringify({defaultPlan:{observer:q,area:expansion.value.area,expansion:expansion.work,wallSubtraction:wall,wallFootprintPreparation:prep},fixtures:'clip, segment early exit, location, rays, raster, terrain beams/cuts, urban cuts, output equivalence, error restoration'},null,2));
`);
