const fs=require('fs'),vm=require('vm');const root=__dirname+'/../source/';
vm.runInThisContext(['geometry.js','wall-shadow2.js','operation-counts.js'].map(f=>fs.readFileSync(root+f,'utf8')).join('\n')+String.raw`
const check=(ok,message)=>{if(!ok)throw Error(message);},equal=(a,b,m)=>check(JSON.stringify(a)===JSON.stringify(b),m),withoutTime=x=>JSON.parse(JSON.stringify(x,(k,v)=>k==='ms'?undefined:v));
function monotone(trace,total,label){check(trace.length>1,label+' missing checkpoints');for(let i=1;i<trace.length;i++)for(const key of Object.keys(emptySolverWork()))check(trace[i][key]>=trace[i-1][key],label+' decreased '+key);equal(trace.at(-1),total,label+' final differs');}
for(const scene of SCENES){for(const q of [scene.observer,...scene.mesh.tris.slice(0,5).map(centroid)]){const e=attachSolverWork(()=>expandVector2(q,scene));equal(withoutTime(measureSolverWork(()=>expandVector2(q,scene)).value),withoutTime(expandVector2(q,scene)),'2D solver output changed');monotone([e.workBeforeVisits,...e.workByVisit],e.work,'2D visits');equal(sumSolverWork(e.workBeforeVisits,...e.workPerVisit),e.work,'Per visit sum');equal(recordedVisitWork(e,{index:0}),e.workBeforeVisits,'Zero processed entries must retain locator work');equal(recordedVisitWork(e,{index:e.visits.length}),e.work,'Complete entry count');const path=[];let k=e.visits.length-1;while(k>=0){path.push(k);k=e.visits[k].parent;}const branch=recordedVisitWork(e,{ids:path});equal(branch,sumSolverWork(e.workBeforeVisits,...path.map(i=>e.workPerVisit[i])),'Branch includes unrelated entries');check(branch.geometricTests<=e.work.geometricTests,'Branch exceeds full work');}}
for(const scene of SCENES){const q=scene.observer,v=attachSolverWork(()=>visibility(q,scene));equal(measureSolverWork(()=>visibility(q,scene)).value,visibility(q,scene),'Event-sector solver output changed');check(v.workBySnapshot.length===v.sectors.length+1,'Missing event interval checkpoints');monotone(v.workBySnapshot,v.work,'Event sectors');const testsPerSector=sceneEdges(scene).length+2;for(let k=0;k<=v.sectors.length;k++)check(recordedSnapshotWork(v,k).rayPrimitiveTests===k*testsPerSector,'Event prefix ray count differs');}
const base=inputTerrain(3,2),q3=[20,30,terrainZ(20,30)+4],model=terrainWithCeiling(base,q3,1),beams=attachSolverWork(()=>expand3(q3,model));equal(measureSolverWork(()=>expand3(q3,model)).value,expand3(q3,model),'3D beams output changed');monotone([beams.workBeforeVisits,...beams.workByVisit],beams.work,'3D visits');equal(sumSolverWork(beams.workBeforeVisits,...beams.workPerVisit),beams.work,'Beam branch additivity');
for(const order of ['near','spiral','mesh']){const seq=occluderOrder(model.tris,q3,order),cuts=attachSolverWork(()=>referenceSurface3(q3,model.tris,seq,true));equal(withoutTime(measureSolverWork(()=>referenceSurface3(q3,model.tris,seq,true)).value),withoutTime(referenceSurface3(q3,model.tris,seq,true)),'Surface loop output changed');check(cuts.workBySnapshot.length===model.tris.length+1,'One checkpoint per occluder');monotone(cuts.workBySnapshot,cuts.work,'Terrain snapshots');check(cuts.workBySnapshot[0].geometricTests===0,'Uncut terrain charged shadow work');for(let k=0;k<=seq.length;k++){const prefix=measureSolverWork(()=>referenceSurface3(q3,model.tris,seq.slice(0,k)));equal(prefix.work,cuts.workBySnapshot[k],'Occluder prefix count mismatch');}for(const id of [0,3,5]){const target=measureSolverWork(()=>{let pieces=[model.tris[id]];for(const i of seq){const h=shadowPlanes(model.tris[i],q3);if(!h)continue;pieces=pieces.flatMap(poly=>h.some(pl=>Math.max(...poly.map(p=>val3(pl,p)))<=E3)?[poly]:subtractShadow(poly,h));}return pieces;});const expected=referenceSurface3(q3,model.tris,seq).pieces[id].polys;equal(target.value,expected,'Receiver-specific clipping mismatch');}}
const urban=urbanModel(),qU=[18,31,28],cut=attachSolverWork(()=>visibility3(qU,urban.receivers,urban.objects,true));equal(measureSolverWork(()=>visibility3(qU,urban.receivers,urban.objects,true)).value,visibility3(qU,urban.receivers,urban.objects,true),'Urban output changed');monotone(cut.workBySnapshot,cut.work,'Urban snapshots');for(let k=0;k<=urban.objects.length;k++)equal(measureSolverWork(()=>visibility3(qU,urban.receivers,urban.objects.slice(0,k))).work,cut.workBySnapshot[k],'Urban prefix mismatch');
const wall=attachSolverWork(()=>subtract2([43,32],SCENES[0]),'wall');monotone(wall.workBySnapshot,wall.work,'Wall snapshots');equal(sumSolverWork(wall.preparation,recordedSnapshotWork(wall,0)),wall.preparation,'Initial wall state omitted preparation');
console.log('PASS: recorded progress monotone; exact final totals; prefix and branch accounting; pinned-loop output equivalence; focused target receivers.');
`);
