/* Progressive receiver traversal, clean acceptance, shared selection and export. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const scratch=path.resolve(__dirname,'../.codex-scratch.nosync');fs.mkdirSync(scratch,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:3840,height:2160},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto(process.env.LAB_URL||'http://127.0.0.1:8764/visibility-lab-v4.html#projection');await page.waitForFunction(()=>window.visibilityLab);
  const setup=await page.evaluate(()=>{visibilityLab.renderAt('projection',0,{variant:'project',qxy:[9,35],density:'regular',face:50,viewFocus:true});const d=terrainState(state),r=G(state),workflow=projectionWorkflow(state,d,{w:r.w*.40,h:405});return {count:workflow.timeline.length,kinds:workflow.timeline.map(s=>s.kind)};});
  assert.ok(setup.count>8);for(const kind of ['viewport','prepare','extend','overlap','retain','reject','accept'])assert.ok(setup.kinds.includes(kind),kind);
  const counts=[],positions=[];let overlap=-1;
  for(let k=0;k<setup.count;k++){
   const data=await page.evaluate(({k,count})=>{visibilityLab.renderAt('projection',(k+.01)/count,{variant:'project',qxy:[9,35],density:'regular',face:50,viewFocus:true});const p=visibilityLab.snapshot(),node=document.querySelector('[data-projection-sequence]'),labels=which=>[...document.querySelectorAll(`[data-terrain-vertices=${which}] [data-point-label]`)].map(el=>[el.dataset.pointLabel,el.getAttribute('fill')]);return {error:p.error,work:p.panel.work.entries[0].work,kind:node.dataset.kind,clean:node.dataset.clean,labels:[labels('main'),labels('observer')],statsTop:document.querySelector('.stats').getBoundingClientRect().top,viewport:document.querySelectorAll('[data-projection-viewport] path').length,original:document.querySelector('[data-current-face-overlay]')!==null,badEdges:[...document.querySelectorAll('[data-terrain-view=main] path,[data-terrain-view=detail] path')].some(p=>[C.orange,C.purple].includes(p.getAttribute('stroke'))),svg:document.querySelector('#view').outerHTML};},{k,count:setup.count});
   assert.equal(data.error,null);assert.equal(data.kind,setup.kinds[k]);assert.equal(data.viewport,4);assert.deepEqual(data.labels[0],data.labels[1],'letters and colors match between views');assert.ok(!/NaN|Infinity/.test(data.svg));counts.push(data.work);positions.push(data.statsTop);
   if(data.kind==='overlap'&&overlap<0)overlap=k;
   if(data.kind==='accept'){assert.equal(data.original,false,'acceptance drops the original target outline');assert.equal(data.clean,'true');assert.equal(data.badEdges,false,'accepted geometry has no orange or purple construction edges');assert.ok(data.labels[0].every(([,color])=>color==='#087e82'));}
  }
  for(let k=1;k<counts.length;k++)for(const key of ['geometricTests','polygonClips','segmentClips'])assert.ok(counts[k][key]>=counts[k-1][key]);
  assert.ok(new Set(counts.map(w=>w.geometricTests)).size>8,'multiple genuine work checkpoints');assert.ok(Math.max(...positions)-Math.min(...positions)<1,'readouts stay anchored through acceptance');
  const crowded=await page.evaluate(()=>{const scale=document.querySelector('#view').getScreenCTM().a,pad=2.25*scale;return ['main','observer'].map(which=>[...document.querySelectorAll(`[data-terrain-vertices=${which}] [data-point-label]`)].map(el=>{const r=el.getBoundingClientRect();return {label:el.dataset.pointLabel,x:r.x-pad,y:r.y-pad,right:r.right+pad,bottom:r.bottom+pad};}));});for(const labels of crowded)for(let i=0;i<labels.length;i++)for(let j=i+1;j<labels.length;j++)assert.ok(!(labels[i].x<labels[j].right&&labels[i].right>labels[j].x&&labels[i].y<labels[j].bottom&&labels[i].bottom>labels[j].y),'cut vertex letters and their white halos do not overlap');
  console.log('✓ Selected receiver shows real intermediate work, matching labels, stable readouts and green-only acceptance.');
  await page.evaluate(({k,count})=>visibilityLab.renderAt('projection',(k+.01)/count,{variant:'project',face:50,qxy:[9,35],density:'regular',viewFocus:true}),{k:overlap,count:setup.count});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(scratch,'projection-overlap-4k.png')});
  await page.evaluate(()=>visibilityLab.renderAt('projection',1,{variant:'project',face:50,qxy:[9,35],density:'regular',viewFocus:true}));await page.screenshot({path:path.join(scratch,'projection-accepted-target-4k.png')});
  const finalWork=await page.evaluate(()=>visibilityLab.snapshot().panel.work.entries[0].work);await page.locator('#phase').fill('0');assert.equal(await page.evaluate(()=>visibilityLab.snapshot().panel.work.entries[0].work.geometricTests),0);await page.locator('#phase').fill('1');assert.deepEqual(await page.evaluate(()=>visibilityLab.snapshot().panel.work.entries[0].work),finalWork);
  const outside=await page.evaluate(()=>{const d=terrainState(state),pc=projector(d.q),frame=projectionFrame([],pc,false),id=d.model.tris.findIndex(poly=>viewportClip(poly,pc,frame).length<3);visibilityLab.renderAt('projection',1,{variant:'project',face:id,viewFocus:false});const p=visibilityLab.snapshot();return {stats:p.panel.stats,work:p.panel.work.entries[0].work,filter:measureSolverWork(()=>viewportClip(d.model.tris[id],pc,frame)).work};});assert.equal(outside.stats[3][1],'0 / 140','off-viewport targets perform no occluder tests');assert.deepEqual(outside.work,outside.filter);
  const accumulated=[];
  for(const phase of [0,.15,.35,.55,.8,1])accumulated.push(await page.evaluate(phase=>{visibilityLab.renderAt('projection',phase,{variant:'accumulate',qxy:[9,35],density:'regular',face:50});const p=visibilityLab.snapshot();return {error:p.error,work:p.panel.work.entries[0].work,processed:Number(document.querySelector('[data-projection-sequence]').dataset.accepted),kind:document.querySelector('[data-projection-sequence]').dataset.kind};},phase));
  for(let k=0;k<accumulated.length;k++){assert.equal(accumulated[k].error,null);if(k){assert.ok(accumulated[k].work.geometricTests>accumulated[k-1].work.geometricTests);assert.ok(accumulated[k].processed>=accumulated[k-1].processed);}}
  assert.equal(accumulated.at(-1).kind,'complete');assert.ok(accumulated.at(-1).processed>30);assert.equal(await page.locator('[data-key=viewFocus]').count(),0,'accumulation keeps one fixed viewport');
  const equality=await page.evaluate(()=>{const d=terrainState(state),g=G(state),w=projectionWorkflow(state,d,{w:g.w*.40,h:405}),ref=getReference(d),a=w.surfaces.reduce((n,f)=>n+area3(f.poly),0),b=ref.surfaces.reduce((n,f)=>n+area3(viewportClip(f.poly,w.pc,w.frame)),0);return {a,b,scope:visibilityLab.snapshot().panel.work.scope};});assert.ok(Math.abs(equality.a-equality.b)<1e-5);assert.equal(equality.scope,'viewport so far');
  await page.screenshot({path:path.join(scratch,'projection-accumulated-4k.png')});console.log('✓ Accumulation visits viewport receivers, progresses counts and equals independently clipped full visibility.');
  // The old static mode is migrated to a completed accumulated result.
  await page.evaluate(()=>visibilityLab.renderAt('projection',.2,{variant:'result'}));assert.equal(await page.evaluate(()=>visibilityLab.getState().variant),'accumulate');assert.equal(await page.evaluate(()=>visibilityLab.getState().phase),1);
  await page.locator('#exportMode').selectOption('panel');const pending=page.waitForEvent('download');await page.locator('#svg').click();const file=path.join(scratch,'projection-accumulated.svg');await(await pending).saveAs(file);const svg=fs.readFileSync(file,'utf8');assert.ok(svg.includes('data-kind="complete"'));assert.ok(svg.includes('Geometric tests'));assert.ok(!/<(?:image|foreignObject)\b/.test(svg));
  await page.setViewportSize({width:1280,height:720});await page.evaluate(()=>visibilityLab.renderAt('projection',1,{variant:'accumulate'}));const small=await page.evaluate(()=>({body:document.querySelector('#explanationBody').getBoundingClientRect().bottom,footer:document.querySelector('#explanationFooter').getBoundingClientRect().top}));assert.ok(small.body<=small.footer,'small previews scroll instead of overlapping explanation and readouts');
  assert.deepEqual(errors,[]);console.log('✓ Rewind, static-mode migration, small-preview flow and clean native SVG export verified.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
