const fs=require('node:fs'),vm=require('node:vm');
const src=__dirname+'/../source/';
vm.runInThisContext(['geometry','operation-counts','ray-reconstruction'].map(n=>fs.readFileSync(src+n+'.js','utf8')).join('\n')+String.raw`
const check=(v,m)=>{if(!v)throw Error(m);};
function field(nx,ny,z){const points=[];for(let y=0;y<=ny;y++)for(let x=0;x<=nx;x++)points.push([100*x/nx,70*y/ny,z(100*x/nx,70*y/ny)]);const tris=[];for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const a=points[y*(nx+1)+x],b=points[y*(nx+1)+x+1],c=points[(y+1)*(nx+1)+x],d=points[(y+1)*(nx+1)+x+1];tris.push([a,b,d],[a,d,c]);}return tris;}
for(const z of [()=>0,(x,y)=>.1*x+.2*y]){const tris=field(10,7,z),q=[35,27,z(35,27)+7],prep=prepareRayReconstruction(tris),raw=rayCube(q,prepare3(tris),16),old=recoverCells(raw,tris),fresh=recoverRaySurface(raw,prep),total=tris.reduce((a,t)=>a+area3(t),0);check(fresh.area<=total+1e-6,'Physical pieces never overlap or exceed original surface');check(fresh.area>old.area+1,'Connected recovery fills source ownership holes on a plane');check(fresh.polys.some(f=>f.owner!==raw.ids[f.cell]),'Recovery crosses real shared edges');check(fresh.polys.every(f=>raw.ids[f.cell]>=0),'No sky cell is filled');const reversed=tris.map(t=>[...t].reverse()),other=recoverRaySurface(rayCube(q,prepare3(reversed),16),prepareRayReconstruction(reversed));check(Math.abs(other.area-fresh.area)<1e-6,'Input triangle winding does not affect terrain sheet recovery');}
const tris=field(10,7,x=>x<=50?x*.4:(100-x)*.4),q=[10,35,12],prep=prepareRayReconstruction(tris),raw=rayCube(q,prepare3(tris),32),fresh=recoverRaySurface(raw,prep);check(fresh.polys.every(f=>val3(prep.planes[f.owner],q)>0),'Back-facing fold is never bridged');const ref=referenceSurface3(q,tris),old=recoverCells(raw,tris),a=surfaceError(ref,old,tris),b=surfaceError(ref,fresh,tris);check(b.xor<a.xor,'Ridge reconstruction improves physical mismatch');const rays=rayCube(q,prepare3(tris),8,false),rays2=rayCube(q,prepare3(tris),8,true);check(rays.ids.every((v,i)=>v===rays2.ids[i]),'Indexed and linear queries preserve winners');
// Disconnected aligned layers have no adjacency: far layer cannot be filled
// merely because it occupies the same angular cell as the foreground winner.
const layers=[[[0,0,0],[100,0,0],[100,70,0]],[[0,0,0],[100,70,0],[0,70,0]],[[0,0,-10],[100,0,-10],[100,70,-10]],[[0,0,-10],[100,70,-10],[0,70,-10]]],lq=[35,27,8],lr=rayCube(lq,prepare3(layers),16),ls=recoverRaySurface(lr,prepareRayReconstruction(layers));check(ls.polys.every(f=>f.owner<2),'Disconnected depth layer is not bridged');
for(let i=0;i<100;i++){const poly=[[0,0,1],[5,0,2],[4,4,3],[0,3,1]],h={n:[Math.sin(i),Math.cos(i),.2],d:i*.03},a=clip3(poly,h),b=rayReconstructionClip(poly,h,emptySolverWork());check(JSON.stringify(a)===JSON.stringify(b),'Scalar clip exactly preserves baseline vertices');check(area3(a)===rayReconstructionArea(a),'Scalar physical area exactly preserves baseline arithmetic');}const square=(x,y)=>[[x,y,0],[x+1,y,0],[x+1,y+1,0],[x,y+1,0]],ring={polys:[]};for(let y=0;y<3;y++)for(let x=0;x<3;x++)if(x!==1||y!==1)ring.polys.push({owner:0,poly:square(x,y)});const groups=raySurfaceDisplayGroups(ring);check(groups.length===1&&groups[0].dissolved,'Display union successfully dissolves a ring');check(groups[0].loops.length===2,'Display ring retains an inner hole');check(groups[0].loops.reduce((n,p)=>n+p.length,0)===8,'Collinear sample seams disappear');
console.log('PASS: connected physical ray sheets; plane ownership holes filled; winding independence; no sky/backface/disconnected-depth bridges; lower ridge mismatch; linear/indexed agreement.');
`);
