const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const url=process.env.LAB_URL||'http://127.0.0.1:8764/visibility-lab-v4.html';
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(url+'#metrics');await page.waitForFunction(()=>window.visibilityLab?.version===4);
 for(const method of ['raycast','raster'])for(const phase of [0,.5,1]){
  await page.evaluate(({method,phase})=>visibilityLab.renderAt('metrics',phase,{dimension:'2d',variant:method,map:1}),{method,phase});
  const a=await page.evaluate(()=>{const g=document.querySelector('[data-sample-comparison]'),d=sampleComparisonData2(state);return {error:visibilityLab.snapshot().error,method:g.dataset.method,count:+g.dataset.sampleCount,drawn:+g.dataset.drawnCount,cells:g.querySelectorAll('[data-grid-cell]').length,expected:d.raster?d.n*d.sample.ny:d.n,stats:d.sample.stats,work:panelData.work,html:document.querySelector('#view').innerHTML};});assert.equal(a.error,null);assert.equal(a.method,method);assert.equal(a.count,a.expected);assert.equal(a.drawn,a.count);if(method==='raster'){assert.equal(a.cells,a.count);assert.ok(a.stats.cellVisits>=a.stats.queries);assert.equal(a.work.entries[1].work.geometricTests,0);}assert.ok(!/\b(?:NaN|Infinity)\b/.test(a.html));
 }
 await page.evaluate(()=>visibilityLab.renderAt('metrics',.1,{variant:'raycast',showRays:false,rayDrawLimit:16}));
 assert.deepEqual(await page.locator('select[data-key=variant] option').allTextContents(),['Raycast','Raster']);assert.equal(await page.getByLabel('Method',{exact:true}).count(),1);
 for(const key of ['rays','sampleBudget','cubeN','sampler','showRays','rayDrawLimit'])assert.equal(await page.locator(`[data-key=${key}]`).count(),0,'removed sampling budget/cap: '+key);
 const count=await page.locator('[data-sample-comparison]').getAttribute('data-sample-count');await page.locator('#next').click();assert.equal(+await page.locator('[data-sample-comparison]').getAttribute('data-sample-count'),+count+1);await page.locator('#prev').click();assert.equal(await page.locator('[data-sample-comparison]').getAttribute('data-sample-count'),count);
 await page.locator('#phase').fill('1');assert.equal(await page.locator('[data-sample-ray]').count(),1024);await page.getByLabel('Method',{exact:true}).selectOption('raster');assert.equal(await page.evaluate(()=>visibilityLab.getState().phase),1);assert.equal(+await page.locator('[data-sample-comparison]').getAttribute('data-sample-count'),128*Math.round(128*.65));assert.equal(await page.locator('#next').isEnabled(),false);
 console.log('✓ 2D resolution slider draws every ray or real binary occupancy cell and reports grid work separately.');
 for(const method of ['raycast','raster'])for(const phase of [0,.125,1]){
  await page.evaluate(({method,phase})=>visibilityLab.renderAt('metrics',phase,{dimension:'3d',variant:method,density:'coarse',rayDisplay:'none'}),{method,phase});
  const a=await page.evaluate(()=>{const g=document.querySelector('[data-sample-comparison]'),d=sampleComparisonData3(state),e=document.querySelector('#explanation'),body=document.querySelector('#explanationBody').getBoundingClientRect(),footer=document.querySelector('#explanationFooter').getBoundingClientRect();return {error:visibilityLab.snapshot().error,count:+g.dataset.sampleCount,drawn:+g.dataset.drawnCount,N:+g.dataset.gridSide,ny:+g.dataset.gridRows,misses:+g.dataset.misses,texels:[...g.querySelectorAll('[data-terrain-texel]')].reduce((n,e)=>n+(+e.dataset.cellCount||1),0),insetCells:+(g.querySelector('[data-sample-cube-grid]')?.dataset.cellCount||0),rayTests:d.raw.work.rayPrimitiveTests,area:d.sample.area,hiddenArea:d.sample.hidden?.reduce((s,f)=>s+area3(f.poly),0),fullArea:d.d.model.tris.reduce((s,t)=>s+area3(t),0),scroll:e.scrollHeight-e.clientHeight,bodyBottom:body.bottom,footerTop:footer.top,compound:g.querySelectorAll('[data-world-compound]').length,html:document.querySelector('#view').innerHTML};});
  assert.equal(a.error,null);assert.equal(a.N,Math.round(method==='raster'?8+248*phase:2+254*phase));assert.equal(a.count,method==='raster'?a.N*a.ny:6*a.N*a.N);assert.ok(a.compound>0,'Surface display uses compound vectors');if(method==='raster'){assert.equal(a.drawn,a.count);assert.equal(a.texels,a.count);assert.equal(a.ny,Math.round(.7*a.N));assert.ok(Math.abs(a.area+a.hiddenArea-a.fullArea)<1e-5,'Texture partitions full physical terrain');assert.equal(a.rayTests,0);}else{assert.equal(a.drawn,0);assert.equal(a.insetCells,a.count,'Every calculated ray is retained in the hit inset');assert.ok(a.misses>0);assert.ok(a.rayTests>0);assert.equal(await page.locator('[data-sample-ray]').count(),0);}
  if(a.scroll>1)await page.screenshot({path:path.join(__dirname,'../.codex-scratch.nosync/sampling-overflow.png')});assert.ok(a.scroll<=1,'Explanation fits1080p: '+JSON.stringify({method,phase,scroll:a.scroll,bodyBottom:a.bodyBottom,footerTop:a.footerTop}));assert.ok(a.bodyBottom<=a.footerTop+1);assert.ok(!/\b(?:NaN|Infinity)\b/.test(a.html));
 }
 await page.evaluate(()=>visibilityLab.renderAt('metrics',.055,{dimension:'3d',variant:'raycast',density:'coarse',rayDisplay:'none'}));const original=await page.evaluate(()=>({count:sampleComparisonData3(state).sample.count,area:sampleComparisonData3(state).sample.area,error:sampleComparisonData3(state).error.xor,work:panelData.work}));
 for(const display of ['all','hits','none']){await page.locator('[data-key=rayDisplay]').selectOption(display);const shown=await page.evaluate(()=>{const g=document.querySelector('[data-sample-comparison]');return {count:+g.dataset.sampleCount,drawn:+g.dataset.drawnCount,misses:+g.dataset.misses,lines:g.querySelectorAll('[data-sample-ray]').length,area:sampleComparisonData3(state).sample.area,error:sampleComparisonData3(state).error.xor,work:panelData.work};});assert.equal(shown.drawn,display==='none'?0:display==='all'?shown.count:shown.count-shown.misses);assert.equal(shown.lines,shown.drawn);assert.equal(shown.area,original.area);assert.equal(shown.error,original.error);assert.deepEqual(shown.work,original.work,'Ray drawing changes no numerical work');}
 for(const method of ['raycast','raster'])for(const compare of ['overlay','side'])await page.evaluate(({method,compare})=>visibilityLab.renderAt('metrics',.025,{dimension:'3d',variant:method,density:'coarse',hidden:true,shadowEnvelope:true,sampleWire:true,compare,rayDisplay:'none'}),{method,compare});
 // Save the final dense comparisons on the normal demonstration mesh. Ray
 // drawing is disabled here so the surface reconstruction remains inspectable.
 for(const method of ['raycast','raster']){
  await page.evaluate(method=>visibilityLab.renderAt('metrics',1,{dimension:'3d',variant:method,density:'regular',hidden:false,shadowEnvelope:false,sampleWire:false,compare:'overlay',rayDisplay:'none',wire:true}),method);
  for(const width of [1920,3840]){await page.setViewportSize({width,height:width*9/16});await page.screenshot({path:path.join(__dirname,`../.codex-scratch.nosync/sampling-${method}-256-${width}.png`)});}
 }
 await page.setViewportSize({width:1920,height:1080});
 assert.deepEqual(await page.locator('select[data-key=variant] option').allTextContents(),['Raycast','Raster']);
 for(const [methodId,N] of [['ray3-indexed',64],['ray3-indexed',256],['raster3-surface',256]]){const a=await page.evaluate(({methodId,N})=>{const info=BENCHMARK_METHODS[methodId],dest=benchmarkDestination({...info,methodId,resolution:N}),s=validate({...DEFAULT,scene:dest.scene,dimension:'3d',variant:dest.variant,phase:dest.phase});return {N:sampleResolution(s)};},{methodId,N});assert.equal(a.N,N,'Benchmark link opens the measured resolution');}
 const legacy=await page.evaluate(()=>{const s=validate({scene:'cost',variant:'raster',dimension:'3d',cubeN:32});return {scene:s.scene,variant:s.variant,N:sampleResolution(s)};});assert.deepEqual(legacy,{scene:'metrics',variant:'raycast',N:32});
 console.log('✓ Connected ray surfaces and complete raster texels support256 grid sides; ray display filters preserve every calculation; inset counts and1080p readouts match.');
 assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
