const fs=require('fs'),vm=require('vm');
global.document={getElementById:()=>({innerHTML:''})};const source=__dirname+'/../source/';
vm.runInThisContext(['geometry.js','operation-counts.js','shadow-stages.js','receiver-boundaries.js','svg-world.js','svg-context.js','scenes.js','terrain-views.js','terrain-shadow-stages.js'].map(f=>fs.readFileSync(source+f,'utf8')).join('\n')+String.raw`
const check=(ok,message)=>{if(!ok)throw Error(message);},equal=(a,b,message)=>check(JSON.stringify(a)===JSON.stringify(b),message);
function original(q,tris,id){const h=shadowPlanes(tris[id],q),remain=[],blocked=[];tris.forEach((t,owner)=>{const off=subtractShadow(t,h);off.forEach(poly=>remain.push({poly,owner,kind:'terrain'}));if(h&&Math.max(...t.map(p=>val3(h[0],p)))>E3){const over=clipByPlanes(t,h);if(over.length>2)blocked.push({poly:over,owner,kind:'terrain'});}});return {remain,blocked};}
for(const dims of [[3,2],[6,4]])for(const qxy of [[9,35],[30,24]]){
 const model=inputTerrain(...dims),q=[...qxy,terrainZ(...qxy)+8];model.roof=Math.max(model.peak,q[2])+1;const d={q,model};
 for(const id of [0,Math.floor(model.tris.length/2),model.tris.length-1]){
  const expected=measureSolverWork(()=>original(q,model.tris,id)),trace=recordedSingleShadow3(q,model.tris,id);equal(trace.remain,expected.value.remain,'Retained geometry differs');equal(trace.blocked,expected.value.blocked,'Shadow patches differ');equal(trace.work,expected.work,'Executed work differs');
  let previous=trace.preparedWork;for(const e of trace.entries)for(const next of [e.classifiedWork,e.overlapWork,e.work]){for(const key of Object.keys(emptySolverWork()))check(next[key]>=previous[key],'Checkpoint decreases');previous=next;}
  equal(previous,trace.work,'Final checkpoint differs');
  const s={...DEFAULT,scene:'terrain',variant:'one',face:id},scene=terrainSingleShadowScene(s,d),n=scene.timeline.length;const extension=scene.timeline.find(t=>t.kind==='extend');check(extension.start===.10&&extension.end===.35,'Extrusion phase allocation differs');check(scene.timeline.filter(t=>t.kind==='extend').length===1,'Extrusion contains pseudo-steps');check(scene.timeline.at(-1).start===.85,'Final hold is too short');equal(scene.phaseStops,scene.timeline.map(t=>t.start),'Phase stops differ');
  for(const phase of [.10,.20,.349999]){const growing=terrainSingleShadowScene({...s,phase},d);check(growing.step.kind==='extend'&&Math.abs(growing.step.grow-(phase-.10)/.25)<1e-10,'Extrusion is not continuous');equal(growing.work,trace.preparedWork,'Display growth invents operation counts');}check(terrainSingleShadowScene({...s,phase:.35},d).step.kind==='classify','Receivers must start at .35');for(const phase of [.85,.9,.99,1])check(terrainSingleShadowScene({...s,phase},d).finished,'Finished state is not held');
  for(const phase of [0,.1,.26,.5,.77,1,.26,1]){const view=terrainSingleShadowScene({...s,phase},d);equal(view.work,scene.timeline[view.stage].work,'Rewind counts changed');if(!view.finished){const source=view.lines.filter(l=>l.sourceRay);check(source.length===3&&source.every(l=>l.occlude===false&&l.a===d.q&&model.tris[id].includes(l.b)),'Source rays do not continuously reach the selected facet');}if(view.step.entry)check(view.faces.some(f=>f.candidate)&&view.lines.some(l=>l.candidate&&l.occlude===false),'Receiver highlight absent');}
  const final=terrainSingleShadowScene({...s,phase:1},d);equal(final.retained,trace.remain,'Final retained scene differs');equal(final.removed,trace.blocked,'Final shadow scene differs');check(!final.lines.some(l=>l.sourceRay||l.candidate),'Final inspection rays persist');
 }
}
const render={...DEFAULT,scene:'terrain',variant:'one',density:'coarse',face:5,phase:.5};ctx.reset();hitTargets=[];drawTerrainSingleShadow(render);const svg=ctx.parts.join('');check(svg.includes('data-terrain-single-sequence="true"')&&svg.includes('data-candidate="'),'Receiver metadata absent');const main=svg.match(/data-terrain-view="main" data-face-count="(\d+)" data-edge-count="(\d+)"/),plan=svg.match(/data-terrain-view="plan" data-face-count="(\d+)" data-edge-count="(\d+)"/);check(main&&plan&&main[1]===plan[1]&&main[2]===plan[2],'Main and plan geometry differ');check(hitTargets.filter(t=>['terrain','terrainPlan'].includes(t.kind)).every(t=>t.selectFaces),'Facet selection disabled');check(panelData.progress.kind==='terrainSingleSequence','Readout scope absent');
console.log('PASS: selected-facet receiver trace matches original geometry and exact work; genuine progressive checkpoints; extension time; continuous source rays; highlighted receiver; stable rewind; main/plan geometry and shared selection.');
`);
