const fs=require('fs'),vm=require('vm'),assert=require('assert');const root=__dirname+'/../source/';
vm.runInThisContext(fs.readFileSync(root+'geometry.js','utf8')+'\n'+fs.readFileSync(root+'wall-shadow2.js','utf8')+String.raw`
const ensure=(ok,msg)=>{if(!ok)throw Error(msg);};let seed=712443,cases=0,pointChecks=0,disjointChecks=0,maxAreaError=0,maxReverseAreaError=0;
const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
for(let map=0;map<SCENES.length;map++){const scene=SCENES[map];for(let k=0;k<200;k++){let q;do{q=[.1+rnd()*99.8,.1+rnd()*64.8];}while(!validObserver(q,scene));const result=subtract2(q,scene),reversed=subtract2(q,scene,'reverse'),exact=visibility(q,scene),expanded=expand(q,scene),error=Math.max(Math.abs(result.area-exact.area),Math.abs(result.area-expanded.area));maxAreaError=Math.max(maxAreaError,error);maxReverseAreaError=Math.max(maxReverseAreaError,Math.abs(result.area-reversed.area));ensure(error<1e-5&&Math.abs(result.area-reversed.area)<1e-5,'Independent area/order comparison');
 ensure(result.snapshots.length===result.edges.length+1&&result.stats.length===result.snapshots.length,'Snapshot accounting');ensure(result.shadows.length===result.edges.length,'Missing wall display shadows');const initialArea=area(scene.outer)-scene.holes.reduce((s,p)=>s+area(p),0);ensure(Math.abs(result.stats[0].area-initialArea)<1e-6,'Initial candidate includes solid footprints');
 for(let i=1;i<result.stats.length;i++){ensure(result.stats[i].area<=result.stats[i-1].area+1e-6,'Nonmonotone subtraction');ensure(Math.abs(result.stats[i-1].area-result.stats[i].area-result.shadows[i-1].area)<1e-6,'Removed fragments not equal area change');ensure(result.stats[i].wallPiecesTested>=result.stats[i-1].wallPiecesTested&&result.stats[i].vertexTests>=result.stats[i-1].vertexTests,'Work counts not cumulative');}
 for(let i=0;i<48;i++){const theta=rnd()*TAU,r=rnd()*115,p=add(q,[r*Math.cos(theta),r*Math.sin(theta)]),h=nearest(q,theta,sceneEdges(scene)),expected=r<h.t,got=result.parts.some(poly=>inside(p,poly)),reverse=reversed.parts.some(poly=>inside(p,poly));ensure(got===expected&&reverse===expected,'Spatial visibility/order disagreement');pointChecks++;}
 if(k<15){for(const p of result.parts){for(const hole of scene.holes)ensure(area(clipConvex(p,hole))<1e-7,'Final piece enters a footprint');ensure(p.every(v=>v[0]>=-1e-7&&v[0]<=100+1e-7&&v[1]>=-1e-7&&v[1]<=65+1e-7),'Piece outside outer receiver');}for(let i=0;i<result.parts.length;i++)for(let j=i+1;j<result.parts.length;j++){ensure(area(clipConvex(result.parts[i],result.parts[j]))<1e-7,'Final pieces overlap');disjointChecks++;}}
 cases++;}}
const q=[0,5],wall={a:[5,3],b:[5,7]},planes=wallShadowPlanes2(q,wall);let shadow=[[-1,0],[10,0],[10,10],[-1,10]];for(const h of planes)shadow=clip(shadow,p=>dot(h.n,p)-h.d);ensure(!inside([3,5],shadow),'Missing supporting base plane removes foreground');ensure(inside([8,5],shadow),'Behind-wall point escapes shadow');ensure(wallShadowPlanes2([5,1],wall)===null&&wallShadowPlanes2([5,5],wall)===null,'Collinear wall shadow should have zero area');
// A supporting-line observer can be free while a nonzero segment lies ahead.
const scene=SCENES[1],collinear=[15,31],result=subtract2(collinear,scene);ensure(Math.abs(result.area-visibility(collinear,scene).area)<1e-5,'Collinear free-space observer area');
const unmeshed={outer:SCENES[0].outer,holes:SCENES[0].holes},unmeshedResult=subtract2([43,32],unmeshed);ensure(Math.abs(unmeshedResult.area-visibility([43,32],unmeshed).area)<1e-5,'Input triangulation required');
const ordinalOrder=Array.from({length:result.edges.length},(_,i)=>result.edges.length-i-1),ordered=subtract2(collinear,scene,ordinalOrder);ensure(Math.abs(ordered.area-result.area)<1e-6,'Ordinal order API');
console.log(JSON.stringify({cases,pointChecks,disjointChecks,maxAreaError,maxReverseAreaError,example:{edges:result.edges.length,preprocessing:result.preprocessing,stats:result.stats.at(-1),area:result.area}},null,2));
`);
