const DEGREES=180/Math.PI;
const MIN_CAMERA_ELEVATION=1/DEGREES,MAX_CAMERA_ELEVATION=89/DEGREES;
function cameraAzimuth(value){return value < -Math.PI || value >= Math.PI ? wrap(value+Math.PI)-Math.PI : value;}
function hydrateReferenceLinks(){document.querySelectorAll('.docs a[data-scene]').forEach(a=>a.href=demonstrationHref({scene:a.dataset.scene,variant:a.dataset.variant,dimension:a.dataset.dimension,raySearch:a.dataset.raySearch,phase:a.dataset.phase===undefined?undefined:+a.dataset.phase}));}
function buildDocs(){const d=DOCS[state.scene];$('docTitle').textContent=d.title;$('methodDoc').innerHTML=d.method;$('detailDoc').innerHTML=d.detail;$('sceneEffort').innerHTML=(d.cost||'')+(['subtraction','expansion'].includes(state.scene)?'<div id="workComparison"></div>':'')+(d.sources?'<details><summary>Sources for this method</summary>'+d.sources+'</details>':'');$('costDoc').innerHTML=COST_HTML;$('workDetailDoc').innerHTML=WORK_DETAIL_HTML;$('sourceDoc').innerHTML=SOURCES_HTML;$('acronymDoc').innerHTML=ACRONYMS_HTML;renderBenchmarkTable();hydrateReferenceLinks();}
function selectControl(label,key,options,after){const el=document.createElement('label');el.className='setting';const span=document.createElement('span');span.textContent=label;const input=document.createElement('select');input.dataset.key=key;input.setAttribute('aria-label',label);options.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;input.append(o);});input.value=state[key];input.onchange=()=>{stopPlaying();const previous=structuredClone(state);state[key]=typeof DEFAULT[key]==='number'?+input.value:input.value;after?.();state=validate(transitionSharedScene(previous,state,key));if(['variant','dimension','raySearch'].includes(key))syncDemonstrationRoute();buildControls();buildDocs();render();};el.append(span,input);return el;}
function sliderControl(label,key,min,max,step=1,get=null,set=null,digits=null){
 const el=document.createElement('label');el.className='setting';
 const span=document.createElement('span');span.textContent=label;
 const row=document.createElement('div');row.className='rangeflex';
 const a=document.createElement('input'),b=document.createElement('input');a.type='range';b.type='number';
 const read=()=>get?get():state[key],format=v=>digits===null?String(v):Number(v).toFixed(digits);
 for(const i of [a,b]){i.min=min;i.max=max;i.step=step;i.value=format(read());i.dataset.key=key;i.setAttribute('aria-label',label+(i===b?' value':''));}
 const act=i=>{stopPlaying();let v=Number(i.value);if(i.value===''||!Number.isFinite(v)){a.value=b.value=format(read());return;}v=clamp(v,min,max);if(digits!==null)v=Number(v.toFixed(digits));if(set)set(v);else state[key]=v;a.value=b.value=format(read());render();};
 a.oninput=()=>act(a);b.onchange=()=>act(b);row.append(a,b);el.append(span,row);return el;
}
function angleControl(label,key,min,max){const el=sliderControl(label+' (°)',key,min,max,.1,()=>state[key]*DEGREES,v=>state[key]=key==='yaw'?cameraAzimuth(v/DEGREES):v/DEGREES,1);el.classList.add('angle-control');return el;}
function checkControl(label,key,after){const el=document.createElement('label');el.className='check';const a=document.createElement('input');a.type='checkbox';a.checked=!!state[key];a.dataset.key=key;a.onchange=()=>{state[key]=a.checked;after?.();render();};el.append(a,document.createTextNode(label));return el;}
function actionControl(text,fn,primary=false){const b=document.createElement('button');b.textContent=text;if(primary)b.className='primary';b.onclick=fn;return b;}
function buildControls(){const m=MODES.find(m=>m.id===state.scene);document.querySelectorAll('#nav button').forEach(b=>b.setAttribute('aria-selected',b.dataset.id===state.scene));const c=$('controls');c.replaceChildren();$('demonstrationControls').replaceChildren();if(m.variants.length>1){const demonstration=selectControl(state.scene==='metrics'?'Method':'Demonstration','variant',m.variants,()=>{if(state.scene!=='metrics')state.phase=0;});demonstration.classList.add('demonstration-setting');$('demonstrationControls').append(demonstration);placeDemonstrationControl(state.panel);}
 if(state.scene==='cost'){const run=actionControl(benchmarkBusy?'Measuring benchmarks…':'Run benchmarks',runBenchmark,true);run.disabled=benchmarkBusy;c.append(run);if(benchResult)c.append(actionControl('Export measured results',()=>download(new Blob([JSON.stringify(benchResult,null,2)],{type:'application/json'}),'visibility-benchmarks.json')));$('help').textContent='Six fixed positions per geometry. All methods use paired inputs; ranges show variation across positions and scenes.';return;}
 if(state.scene==='metrics')c.append(selectControl('Dimension','dimension',[['2d','2D: planar area / walls'],['3d','3D: terrain surface area']],()=>{state.phase=0;state.shadowEnvelope=false;}));
 const is2=['expansion','subtraction'].includes(state.scene)||state.scene==='metrics'&&state.dimension==='2d';
 const is3=['air','terrain','projection'].includes(state.scene)||state.scene==='metrics'&&state.dimension==='3d';
 if(is2)c.append(selectControl('Plan geometry','map',SCENES.map((s,i)=>[i,s.name])));
 if(state.scene==='expansion'){c.append(selectControl('Point location','locator',[['index','Bounding-box tree + side tests'],['scan','Linear triangle scan']]));if(state.variant==='opening')c.append(sliderControl('Opening entry (0 = automatically chosen)','opening',0,80));c.append(checkControl('Input triangulation','wire'),checkControl('Keep completed cut edges','cuts'));}
 if(state.scene==='subtraction')c.append(checkControl('Retained shadow boundaries','cuts'));
 if(state.scene==='shadows'){c.append(sliderControl('Source height (m)','lightHeight',2,40,.25,()=>state.light[2],v=>state.light[2]=v));c.append(checkControl('Show construction','construction',stopPlaying),checkControl('Plan inset','inset'));}
 if(is3){c.append(sliderControl('Eye height above terrain (m)','eye',1,30,.25));c.append(selectControl('Terrain complexity','density',[['coarse','48 terrain triangles'],['regular','140 terrain triangles'],['fine','192 terrain triangles']]));}
 if(state.scene==='air'){c.append(sliderControl('Ceiling clearance above max height (m)','ceiling',.25,10,.25),checkControl('Entire 3D air-cell wireframe','airWire'),sliderControl('Air-cell wire opacity','airOpacity',.1,1,.05,null,null,2),checkControl('Previous clipped air cells (one branch)','history'));}
 if(state.scene==='projection'&&state.variant==='project')c.append(checkControl('Enlarge target in observer view','viewFocus'));
 if(['terrain','projection'].includes(state.scene)){c.append(selectControl('Occluder processing order','order',[['near','Near → far by centroid distance'],['spiral','Outward rings + angular spiral'],['mesh','Stored mesh order'],['shuffle','Diagnostic: deterministic shuffle']]));}
 if(state.scene==='air'&&state.variant==='project'||state.scene==='terrain'&&state.variant==='one'||state.scene==='projection'&&state.variant==='project'){const selected=document.createElement('span');selected.className='setting';selected.textContent=state.face<0?'Target face: automatic':'Target face: '+state.face;c.append(selected,actionControl('Automatic target',()=>{state.face=-1;captureSharedScene(state);buildControls();render();}));}
 if(['air','terrain','projection'].includes(state.scene)){c.append(checkControl('Input ground triangulation','wire'),checkControl('Keep completed cut edges','cuts'));if(state.scene!=='projection')c.append(checkControl(state.scene==='air'?'Linked insets':'Plan inset','inset'));}
 if(state.scene==='metrics'&&state.variant==='raycast')c.append(selectControl('Raycast search','raySearch',[['indexed','Bounding-volume hierarchy'],['linear','Linear primitive scan']]));
 if(state.scene==='metrics'&&state.dimension==='2d'&&state.variant==='raycast')c.append(selectControl('Measurement','metric',[['area','Area of the filled polygons'],['walls','Wall lengths and open directions']]));
 if(state.scene==='metrics'&&state.dimension==='3d')c.append(selectControl('Comparison layout','compare',[['overlay','Overlay geometry and samples'],['side','Side by side']]),checkControl('Show hidden surface instead','hidden'),checkControl('Extrude each result’s shadow boundaries','shadowEnvelope'),checkControl('Show sampled cell edges','sampleWire'),checkControl('Input terrain mesh','wire'));
 if(is3||state.scene==='shadows'){c.append(sliderControl('Illustration zoom','zoom',.5,4,.05,null,null,2),angleControl('Illustration azimuth','yaw',-180,180),angleControl('Illustration elevation','pitch',1,89));}
 c.append(checkControl('Small object / vertex labels','labels'));$('panelToggle').checked=state.panel;$('exportMode').value=state.exportMode;$('duration').value=String(state.duration);$('play').textContent=playing?'Pause':'Play';
 $('help').textContent=state.scene==='metrics'?(state.dimension==='3d'?'Drag the observer or orbit the background; scroll to zoom. The main slider sets sampling resolution.':'Drag the observer; the main slider sets sampling resolution. ← / → changes one resolution step.'):is2?'Drag the purple observer in free space. ← / → step through the construction.':'Drag the purple observer to move it; drag the background to orbit; scroll the main view to zoom. Click a terrain face to select it in target modes.';
}
