function validate(input){const out=structuredClone(DEFAULT);for(const k of Object.keys(DEFAULT))if(Object.hasOwn(input,k))out[k]=input[k];for(const key of ['panel','wire','airWire','cuts','history','labels','inset','construction','hidden','shadowEnvelope','showRays','sampleWire','viewFocus','candidates'])out[key]=!!out[key];if(!Object.hasOwn(input,'panel'))out.panel=true;const ranges={phase:[0,1],duration:[2,60],map:[0,2],eye:[1,30],yaw:[-1000000,1000000],pitch:[MIN_CAMERA_ELEVATION,MAX_CAMERA_ELEVATION],ceiling:[.25,10],zoom:[.5,4],airOpacity:[.1,1],face:[-1,1000],rays:[8,4096],sampleBudget:[140,65536],cubeN:[2,128],rayDrawLimit:[16,2048],opening:[0,1000],rasterN:[8,192]};for(const [k,[a,b]] of Object.entries(ranges)){const v=Number(out[k]);out[k]=Number.isFinite(v)?clamp(v,a,b):DEFAULT[k];if(['map','rays','cubeN','opening','face','rasterN','sampleBudget','rayDrawLimit'].includes(k))out[k]=Math.round(out[k]);}out.yaw=cameraAzimuth(out.yaw);if(!MODES.some(m=>m.id===out.scene))out.scene=DEFAULT.scene;if(out.scene==='expansion'&&out.variant==='subtract')out.scene='subtraction';if(out.scene==='shadows'&&!Object.hasOwn(input,'construction')&&['surface','isovist'].includes(input.variant))out.construction=false;if(out.variant==='result'&&['air','terrain'].includes(out.scene)){out.variant=out.scene==='air'?'expand':'all';out.phase=1;}const mode=MODES.find(m=>m.id===out.scene);if(!mode.variants.some(v=>v[0]===out.variant))out.variant=mode.variants[0][0];for(const [key,opts] of Object.entries({dimension:['2d','3d'],metric:['area','walls'],density:['coarse','regular','fine'],compare:['overlay','side'],sampler:['surface','angular','raster'],locator:['index','scan'],order:['near','spiral','mesh','shuffle'],exportMode:['graphics','panel']}))if(!opts.includes(out[key]))out[key]=DEFAULT[key];if(!Array.isArray(out.q2)||out.q2.length!==2||!out.q2.every(Number.isFinite)||!validObserver(out.q2,SCENES[out.map]))out.q2=[...SCENES[out.map].observer];if(!Array.isArray(out.qxy)||out.qxy.length!==2||!out.qxy.every(Number.isFinite))out.qxy=[9,35];out.qxy=[clamp(out.qxy[0],1,99),clamp(out.qxy[1],1,69)];if(!Array.isArray(out.light)||out.light.length!==3||!out.light.every(Number.isFinite))out.light=[...DEFAULT.light];out.face=out.face<0?-1:Math.min(out.face,baseModel(out).tris.length-1);out.light=[clamp(out.light[0],1,99),clamp(out.light[1],1,69),clamp(out.light[2],2,40)];return out;}
function stopPlaying(){playing=false;$('play').textContent='Play';}
function setScene(id){if(exporting||benchmarkBusy)return;captureSharedScene(state);savedTabs.set(state.scene,structuredClone(state));const common={panel:state.panel,exportMode:state.exportMode};state=savedTabs.has(id)?structuredClone(savedTabs.get(id)):{...structuredClone(DEFAULT),scene:id,variant:MODES.find(m=>m.id===id).variants[0][0]};Object.assign(state,common);applySharedScene(state);anchorMovingObserver(state);stopPlaying();history.replaceState(null,'','#'+id);buildControls();buildDocs();render();}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
async function quickChecks(){stopPlaying();$('status').textContent='Running independent geometry checks…';await pauseUI();try{let n=0;for(let map=0;map<3;map++)for(let i=0;i<12;i++){const q=[8+(i*19%84),4+(i*13%56)];if(!validObserver(q,SCENES[map]))continue;const a=expandVector2(q,SCENES[map]),b=visibility(q,SCENES[map]);if(Math.abs(a.area-b.area)>1e-5)throw Error('2D area disagreement');n++;}const d=terrainState({...DEFAULT}),ref=getReference(d),beams=getBeams(d);if(Math.abs(ref.area-beams.surfaceArea)>1e-4)throw Error('3D beam/clipping disagreement');const a=rayCube(d.q,d.base.prepared,12,true),b=rasterCube(d.q,d.model.tris,12);let diff=0;for(let i=0;i<a.ids.length;i++)if(a.ids[i]!==b.ids[i])diff++;if(diff)throw Error('Ray/raster winning-face disagreement: '+diff);const pc=projector(d.q),right=pc.point(add(d.q,add(mul(pc.f,10),mul(pc.r,2))));if(Math.abs(right[0]-.2)>1e-9)throw Error('Camera handedness test failed');$('status').textContent=`Passed: ${n} 2D area comparisons; 3D beam/clip area agreement; ${a.ids.length} ray/raster winners; camera handedness. These are checks, not an exact-arithmetic proof.`;}catch(e){$('status').textContent='Check failed: '+e.message;console.error(e);}}
for(const m of MODES){const b=document.createElement('button');b.textContent=m.name;b.dataset.id=m.id;b.onclick=()=>setScene(m.id);$('nav').append(b);}
$('play').onclick=()=>{if(exporting||benchmarkBusy||state.scene==='shadows'&&!state.construction)return;if(playing){stopPlaying();return;}if(state.phase>=1)state.phase=0;playing=true;playStart=NOW();phaseStart=state.phase;$('play').textContent='Pause';};
$('restart').onclick=()=>{stopPlaying();state.phase=0;render();};
function stepBy(dir){if(state.scene==='shadows'&&!state.construction)return;stopPlaying();const step=Math.floor(state.phase*stepCount+1e-6),next=clamp(step+dir,0,stepCount);state.phase=next===stepCount?1:Math.min(1,(next+.03)/stepCount);render();}
$('prev').onclick=()=>stepBy(-1);$('next').onclick=()=>stepBy(1);$('phase').oninput=e=>{stopPlaying();state.phase=+e.target.value;render();};$('duration').onchange=e=>state.duration=+e.target.value;
$('panelToggle').onchange=e=>{state.panel=e.target.checked;render();};$('exportMode').onchange=e=>state.exportMode=e.target.value;
$('png').onclick=()=>saveGraphic('png');$('svg').onclick=()=>saveGraphic('svg');
$('save').onclick=()=>{captureSharedScene(state);download(new Blob([JSON.stringify({...effectiveObserverState(state),sharedScenes:structuredClone(sharedScenes)},null,2)],{type:'application/json'}),'visibility-lab-v4-settings.json');};
$('load').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const loaded=JSON.parse(await file.text());restoreSharedScenes(loaded.sharedScenes);state=validate(loaded);anchorMovingObserver(state);captureSharedScene(state);stopPlaying();history.replaceState(null,'','#'+state.scene);buildControls();buildDocs();render();}catch(err){$('status').textContent='Could not load settings: '+err.message;}e.target.value='';};
$('reset').onclick=()=>{const id=state.scene,panel=state.panel,exportMode=state.exportMode;state={...structuredClone(DEFAULT),scene:id,variant:MODES.find(m=>m.id===id).variants[0][0],panel,exportMode};movingObserverAnchor=null;captureSharedScene(state);stopPlaying();buildControls();buildDocs();render();};$('tests').onclick=quickChecks;
function syncTransport(){const locating=state.scene==='expansion'&&state.variant==='locate';$('timingLabel').textContent=locating?'Duration':'Loop';$('duration').setAttribute('aria-label',locating?'Search duration':'Animation loop duration');const disabled=exporting||benchmarkBusy||state.scene==='shadows'&&!state.construction;for(const id of ['play','restart','prev','next','phase','duration'])$(id).disabled=disabled;if(locating){$('next').disabled=disabled||state.phase>=1;$('prev').disabled=disabled||state.phase<=0;}}
function lockControls(locked){document.querySelectorAll('#presentation button,#presentation input,#presentation select').forEach(el=>el.disabled=locked);if(!locked)syncTransport();}
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){$('status').textContent='Full screen unavailable: '+e.message;}};
// Open shared definitions without replacing the selected demonstration's hash.
document.querySelector('.docs').addEventListener('click',e=>{if(!e.target.closest('a[href="#lab-glossary"]'))return;e.preventDefault();const glossary=$('lab-glossary');glossary.closest('details').open=true;glossary.setAttribute('tabindex','-1');glossary.scrollIntoView({block:'start'});glossary.focus({preventScroll:true});});
document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Exit full screen':'Full screen';render();});
let drag=null,pointerPending=null,pointerFrame=0;
const pointEvent=e=>{const matrix=view.getScreenCTM();if(!matrix)return [0,0];const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());return [p.x,p.y];};
const targetContains=(t,p)=>p[0]>=t.rect.x&&p[0]<=t.rect.x+t.rect.w&&p[1]>=t.rect.y&&p[1]<=t.rect.y+t.rect.h;
function terrainFaceAt(target,p){const tris=target.triangles;if(!tris)return -1;if(target.m){const q=target.m.inverse(p);return tris.findIndex(t=>{const signs=t.map((a,i)=>cross(sub(t[(i+1)%3],a),sub(q,a)));return signs.every(v=>v>=-1e-8)||signs.every(v=>v<=1e-8);});}const cam=target.cam;if(!cam)return -1;const x=(p[0]-cam.rect.x-cam.rect.w/2)/cam.scale,y=-(p[1]-cam.rect.y-cam.rect.h/2)/cam.scale,origin=add(add(add(cam.center,mul(cam.right,x)),mul(cam.up,y)),mul(cam.toward,1000)),direction=mul(cam.toward,-1);let best=Infinity,id=-1;tris.forEach((tri,i)=>{const r=rayTri3(origin,direction,tri);if(r!==null&&r<best){best=r;id=i;}});return id;}
view.addEventListener('wheel',e=>{if(exporting||benchmarkBusy)return;const p=pointEvent(e);if(hitTargets.some(t=>(t.m||t.inset)&&targetContains(t,p)))return;const main=hitTargets.find(t=>t.cam&&['terrain','light'].includes(t.kind)&&targetContains(t,p));if(!main)return;e.preventDefault();stopPlaying();const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?300:1);state.zoom=clamp(state.zoom*Math.exp(-delta*.0015),.5,4);render();buildControls();},{passive:false});
view.addEventListener('pointerdown',e=>{if(exporting||benchmarkBusy||e.button!==0)return;if(e.target.closest('text'))return;const p=pointEvent(e),target=hitTargets.find(t=>t.point&&norm(sub(t.point,p))<30);stopPlaying();view.setPointerCapture(e.pointerId);if(target&&state.variant==='move'){const effective=effectiveObserverState(state);state.q2=effective.q2;state.qxy=effective.qxy;state.variant='still';movingObserverAnchor=null;buildControls();}const origin={last:p,startClient:[e.clientX,e.clientY],moved:false};if(target)drag={...target,...origin};else{const inset=hitTargets.find(t=>(t.m||t.inset)&&targetContains(t,p));if(inset)drag={kind:'background',target:inset,...origin};else{const main=hitTargets.find(t=>t.cam&&targetContains(t,p));if(main)drag={kind:'orbit',target:main,...origin};}}});
function applyPointer(p){if(!drag||!drag.moved)return;if(drag.kind==='background')return;if(drag.kind==='orbit'){state.yaw=cameraAzimuth(state.yaw-(p[0]-drag.last[0])*.004);state.pitch=clamp(state.pitch+(p[1]-drag.last[1])*.003,MIN_CAMERA_ELEVATION,MAX_CAMERA_ELEVATION);drag.last=p;render();return;}const z=drag.kind==='light'?state.light[2]:drag.kind==='terrain'?terrainState(state).q[2]:0;let q=drag.m?drag.m.inverse(p):drag.cam.inverseZ(p,z);if(drag.kind==='map2'){if(validObserver(q,SCENES[state.map]))state.q2=q;}else if(drag.kind==='light'||drag.kind==='lightPlan'){q=[clamp(q[0],1,99),clamp(q[1],1,69),state.light[2]];if(!URBAN3.boxes.some(b=>q[0]>b[0]&&q[0]<b[0]+b[2]&&q[1]>b[1]&&q[1]<b[1]+b[3]&&q[2]<b[4]))state.light=q;}else state.qxy=[clamp(q[0],1,99),clamp(q[1],1,69)];render();}
view.addEventListener('pointermove',e=>{if(!drag)return;if(Math.hypot(e.clientX-drag.startClient[0],e.clientY-drag.startClient[1])>=4)drag.moved=true;pointerPending=pointEvent(e);if(!pointerFrame)pointerFrame=requestAnimationFrame(()=>{pointerFrame=0;const p=pointerPending;pointerPending=null;if(p)applyPointer(p);});});view.addEventListener('pointerup',e=>{if(!drag)return;if(pointerPending){applyPointer(pointerPending);pointerPending=null;}if(!drag.moved){const target=drag.target;if(target?.selectFaces){const id=terrainFaceAt(target,pointEvent(e));if(id>=0){state.face=id;captureSharedScene(state);render();}}}drag=null;buildControls();});view.addEventListener('pointercancel',()=>{drag=null;pointerPending=null;});
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||exporting||benchmarkBusy)return;if(e.code==='Space'){e.preventDefault();$('play').click();}else if(e.key==='ArrowRight'){e.preventDefault();stepBy(1);}else if(e.key==='ArrowLeft'){e.preventDefault();stepBy(-1);}else if(/^[1-9]$/.test(e.key))setScene(MODES[+e.key-1].id);});
function tick(t){if(playing&&!exporting&&!benchmarkBusy){const elapsed=(t-playStart)/1000/state.duration+phaseStart;if(state.scene==='expansion'&&state.variant==='locate'&&elapsed>=1){state.phase=1;stopPlaying();}else state.phase=elapsed%1;render();}requestAnimationFrame(tick);}
window.visibilityLab={version:4,getState:()=>structuredClone(state),setState:s=>{state=stateWithSharedScene(state,s);stopPlaying();buildControls();buildDocs();render();},renderAt:(scene,phase,settings={})=>{captureSharedScene(state);state=validate({...DEFAULT,...settings,scene,phase});movingObserverAnchor=null;captureSharedScene(state);stopPlaying();buildControls();buildDocs();render();return graphicSVG();},exportSVG:svgForExport,snapshot:()=>({panel:panelData,steps:stepCount,state:structuredClone(state),error:window.lastLabError||null}),render,runBenchmark,quickChecks,benchmark:()=>benchResult,geometry:{expandVector2,visibility,locate2,SCENES,terrainState,referenceSurface3,expand3,rayCube,rasterCube,recoverCells,prepare3,surfaceError,surfacePatches,sampleSurface,projector,singleShadow,occluderOrder},hitTargets:()=>hitTargets,sharedScenes:()=>structuredClone(sharedScenes)};
let resizeFrame=0;
new ResizeObserver(()=>{if(!resizeFrame)resizeFrame=requestAnimationFrame(()=>{resizeFrame=0;render();});}).observe(view.parentElement);
const hash=location.hash.slice(1);if(MODES.some(m=>m.id===hash)){state.scene=hash;state.variant=MODES.find(m=>m.id===hash).variants[0][0];}
buildControls();buildDocs();render();requestAnimationFrame(tick);
