function validate(input){const out=structuredClone(DEFAULT);for(const k of Object.keys(DEFAULT))if(Object.hasOwn(input,k))out[k]=input[k];for(const key of ['panel','wire','airWire','cuts','history','labels','inset','construction','hidden','shadowEnvelope','showRays','sampleWire','viewFocus','candidates'])out[key]=!!out[key];if(!Object.hasOwn(input,'panel'))out.panel=true;const ranges={phase:[0,1],duration:[2,60],map:[0,2],eye:[1,30],yaw:[-1000000,1000000],pitch:[MIN_CAMERA_ELEVATION,MAX_CAMERA_ELEVATION],ceiling:[.25,10],face:[-1,1000],rays:[8,4096],sampleBudget:[140,65536],cubeN:[2,128],rayDrawLimit:[16,2048],opening:[0,1000],rasterN:[8,192]};for(const [k,[a,b]] of Object.entries(ranges)){const v=Number(out[k]);out[k]=Number.isFinite(v)?clamp(v,a,b):DEFAULT[k];if(['map','rays','cubeN','opening','face','rasterN','sampleBudget','rayDrawLimit'].includes(k))out[k]=Math.round(out[k]);}out.yaw=cameraAzimuth(out.yaw);if(!MODES.some(m=>m.id===out.scene))out.scene=DEFAULT.scene;if(out.scene==='shadows'&&!Object.hasOwn(input,'construction')&&['surface','isovist'].includes(input.variant))out.construction=false;const mode=MODES.find(m=>m.id===out.scene);if(!mode.variants.some(v=>v[0]===out.variant))out.variant=mode.variants[0][0];for(const [key,opts] of Object.entries({dimension:['2d','3d'],metric:['area','walls'],density:['coarse','regular','fine'],compare:['overlay','side'],sampler:['surface','angular','raster'],locator:['index','scan'],order:['near','spiral','mesh','shuffle'],exportMode:['graphics','panel']}))if(!opts.includes(out[key]))out[key]=DEFAULT[key];if(!Array.isArray(out.q2)||out.q2.length!==2||!out.q2.every(Number.isFinite)||!validObserver(out.q2,SCENES[out.map]))out.q2=[...SCENES[out.map].observer];if(!Array.isArray(out.qxy)||out.qxy.length!==2||!out.qxy.every(Number.isFinite))out.qxy=[9,35];out.qxy=[clamp(out.qxy[0],1,99),clamp(out.qxy[1],1,69)];if(!Array.isArray(out.light)||out.light.length!==3||!out.light.every(Number.isFinite))out.light=[...DEFAULT.light];out.light=[clamp(out.light[0],1,99),clamp(out.light[1],1,69),clamp(out.light[2],2,40)];return out;}
function stopPlaying(){playing=false;$('play').textContent='Play';}
function setScene(id){if(exporting||benchmarkBusy)return;savedTabs.set(state.scene,structuredClone(state));const common={panel:state.panel,exportMode:state.exportMode};state=savedTabs.has(id)?structuredClone(savedTabs.get(id)):{...structuredClone(DEFAULT),scene:id,variant:MODES.find(m=>m.id===id).variants[0][0]};Object.assign(state,common);stopPlaying();history.replaceState(null,'','#'+id);buildControls();buildDocs();render();}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
async function quickChecks(){stopPlaying();$('status').textContent='Running independent geometry checks…';await pauseUI();try{let n=0;for(let map=0;map<3;map++)for(let i=0;i<12;i++){const q=[8+(i*19%84),4+(i*13%56)];if(!validObserver(q,SCENES[map]))continue;const a=expandVector2(q,SCENES[map]),b=visibility(q,SCENES[map]);if(Math.abs(a.area-b.area)>1e-5)throw Error('2D area disagreement');n++;}const d=terrainState({...DEFAULT}),ref=getReference(d),beams=getBeams(d);if(Math.abs(ref.area-beams.surfaceArea)>1e-4)throw Error('3D beam/clipping disagreement');const a=rayCube(d.q,d.base.prepared,12,true),b=rasterCube(d.q,d.model.tris,12);let diff=0;for(let i=0;i<a.ids.length;i++)if(a.ids[i]!==b.ids[i])diff++;if(diff)throw Error('Ray/raster winning-face disagreement: '+diff);const pc=projector(d.q),right=pc.point(add(d.q,add(mul(pc.f,10),mul(pc.r,2))));if(Math.abs(right[0]-.2)>1e-9)throw Error('Camera handedness test failed');$('status').textContent=`Passed: ${n} 2D area comparisons; 3D beam/clip area agreement; ${a.ids.length} ray/raster winners; camera handedness. These are checks, not an exact-arithmetic proof.`;}catch(e){$('status').textContent='Check failed: '+e.message;console.error(e);}}
for(const m of MODES){const b=document.createElement('button');b.textContent=m.name;b.dataset.id=m.id;b.onclick=()=>setScene(m.id);$('nav').append(b);}
$('play').onclick=()=>{if(exporting||benchmarkBusy||state.scene==='shadows'&&!state.construction)return;if(playing){stopPlaying();return;}if(state.phase>=1)state.phase=0;playing=true;playStart=NOW();phaseStart=state.phase;$('play').textContent='Pause';};
$('restart').onclick=()=>{stopPlaying();state.phase=0;render();};
function stepBy(dir){if(state.scene==='shadows'&&!state.construction)return;stopPlaying();const step=Math.floor(state.phase*stepCount+1e-6),next=clamp(step+dir,0,stepCount);state.phase=next===stepCount?1:Math.min(1,(next+.03)/stepCount);render();}
$('prev').onclick=()=>stepBy(-1);$('next').onclick=()=>stepBy(1);$('phase').oninput=e=>{stopPlaying();state.phase=+e.target.value;render();};$('duration').onchange=e=>state.duration=+e.target.value;
$('panelToggle').onchange=e=>{state.panel=e.target.checked;render();};$('exportMode').onchange=e=>state.exportMode=e.target.value;
$('png').onclick=()=>saveGraphic('png');$('svg').onclick=()=>saveGraphic('svg');
$('save').onclick=()=>download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'visibility-lab-v4-settings.json');
$('load').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{state=validate(JSON.parse(await file.text()));stopPlaying();buildControls();buildDocs();render();}catch(err){$('status').textContent='Could not load settings: '+err.message;}e.target.value='';};
$('reset').onclick=()=>{const id=state.scene,panel=state.panel,exportMode=state.exportMode;state={...structuredClone(DEFAULT),scene:id,variant:MODES.find(m=>m.id===id).variants[0][0],panel,exportMode};stopPlaying();buildControls();buildDocs();render();};$('tests').onclick=quickChecks;
function syncTransport(){const disabled=exporting||benchmarkBusy||state.scene==='shadows'&&!state.construction;for(const id of ['play','restart','prev','next','phase','duration'])$(id).disabled=disabled;}
function lockControls(locked){document.querySelectorAll('#presentation button,#presentation input,#presentation select').forEach(el=>el.disabled=locked);if(!locked)syncTransport();}
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){$('status').textContent='Full screen unavailable: '+e.message;}};
document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Exit full screen':'Full screen';render();});
let drag=null,pointerPending=null,pointerFrame=0;
const pointEvent=e=>{const matrix=view.getScreenCTM();if(!matrix)return [0,0];const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());return [p.x,p.y];};
view.addEventListener('pointerdown',e=>{if(exporting||benchmarkBusy)return;if(e.target.closest('text'))return;const p=pointEvent(e),target=hitTargets.find(t=>norm(sub(t.point,p))<30);stopPlaying();view.setPointerCapture(e.pointerId);if(target&&state.variant==='move'){if(state.dimension==='2d'){state.q2=[8+84*state.phase,32];state.variant='still';}else{state.qxy=[8+77*state.phase,35];state.variant='still';}buildControls();}if(target)drag={...target,last:p};else{const inRect=t=>p[0]>=t.rect.x&&p[0]<=t.rect.x+t.rect.w&&p[1]>=t.rect.y&&p[1]<=t.rect.y+t.rect.h;const map=hitTargets.find(t=>t.kind==='map2'&&inRect(t));if(map)drag={...map,last:p};else if(hitTargets.some(t=>t.cam&&inRect(t)))drag={kind:'orbit',last:p};}});
function applyPointer(p){if(!drag)return;if(drag.kind==='orbit'){state.yaw=cameraAzimuth(state.yaw-(p[0]-drag.last[0])*.004);state.pitch=clamp(state.pitch+(p[1]-drag.last[1])*.003,MIN_CAMERA_ELEVATION,MAX_CAMERA_ELEVATION);drag.last=p;render();return;}const z=drag.kind==='light'?state.light[2]:drag.kind==='terrain'?terrainState(state).q[2]:0;let q=drag.m?drag.m.inverse(p):drag.cam.inverseZ(p,z);if(drag.kind==='map2'){if(validObserver(q,SCENES[state.map]))state.q2=q;}else if(drag.kind==='light'||drag.kind==='lightPlan'){q=[clamp(q[0],1,99),clamp(q[1],1,69),state.light[2]];if(!URBAN3.boxes.some(b=>q[0]>b[0]&&q[0]<b[0]+b[2]&&q[1]>b[1]&&q[1]<b[1]+b[3]&&q[2]<b[4]))state.light=q;}else state.qxy=[clamp(q[0],1,99),clamp(q[1],1,69)];render();}
view.addEventListener('pointermove',e=>{if(!drag)return;pointerPending=pointEvent(e);if(!pointerFrame)pointerFrame=requestAnimationFrame(()=>{pointerFrame=0;const p=pointerPending;pointerPending=null;applyPointer(p);});});view.addEventListener('pointerup',()=>{if(pointerPending){applyPointer(pointerPending);pointerPending=null;}drag=null;buildControls();});view.addEventListener('pointercancel',()=>drag=null);
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||exporting||benchmarkBusy)return;if(e.code==='Space'){e.preventDefault();$('play').click();}else if(e.key==='ArrowRight'){e.preventDefault();stepBy(1);}else if(e.key==='ArrowLeft'){e.preventDefault();stepBy(-1);}else if(/^[1-8]$/.test(e.key))setScene(MODES[+e.key-1].id);});
function tick(t){if(playing&&!exporting&&!benchmarkBusy){const elapsed=(t-playStart)/1000/state.duration+phaseStart;state.phase=elapsed%1;render();}requestAnimationFrame(tick);}
window.visibilityLab={version:4,getState:()=>structuredClone(state),setState:s=>{state=validate({...state,...s});stopPlaying();buildControls();buildDocs();render();},renderAt:(scene,phase,settings={})=>{state=validate({...DEFAULT,...settings,scene,phase});stopPlaying();buildControls();buildDocs();render();return graphicSVG();},exportSVG:svgForExport,snapshot:()=>({panel:panelData,steps:stepCount,state:structuredClone(state),error:window.lastLabError||null}),render,runBenchmark,quickChecks,benchmark:()=>benchResult,geometry:{expandVector2,visibility,locate2,SCENES,terrainState,referenceSurface3,expand3,rayCube,rasterCube,recoverCells,prepare3,surfaceError,surfacePatches,sampleSurface,projector,singleShadow,occluderOrder},hitTargets:()=>hitTargets};
let resizeFrame=0;
new ResizeObserver(()=>{if(!resizeFrame)resizeFrame=requestAnimationFrame(()=>{resizeFrame=0;render();});}).observe(view.parentElement);
const hash=location.hash.slice(1);if(MODES.some(m=>m.id===hash)){state.scene=hash;state.variant=MODES.find(m=>m.id===hash).variants[0][0];}
buildControls();buildDocs();render();requestAnimationFrame(tick);
