// Observer and input geometry belong to scene families; demonstration controls remain tab-local.
const sharedScenes={plan:{map:DEFAULT.map,observers:SCENES.map(s=>[...s.observer])},terrain:{qxy:[...DEFAULT.qxy],density:DEFAULT.density,eye:DEFAULT.eye,ceiling:DEFAULT.ceiling},urban:{light:[...DEFAULT.light]}};
sharedScenes.plan.observers[DEFAULT.map]=[...DEFAULT.q2];
function sceneFamily(s){return ['expansion','subtraction','events'].includes(s.scene)||['metrics','cost'].includes(s.scene)&&s.dimension==='2d'?'plan':['air','terrain','projection'].includes(s.scene)||['metrics','cost'].includes(s.scene)&&s.dimension==='3d'?'terrain':'urban';}
let movingObserverAnchor=null;
function anchorMovingObserver(s){movingObserverAnchor=s.scene==='metrics'&&s.variant==='move'?{family:sceneFamily(s),phase:s.phase,q:[...(s.dimension==='2d'?s.q2:s.qxy)]}:null;}
function effectiveObserverState(s){const out=structuredClone(s);if(s.scene==='metrics'&&s.variant==='move'){const family=sceneFamily(s),anchor=movingObserverAnchor?.family===family?movingObserverAnchor:null,delta=s.phase-(anchor?.phase||0);if(s.dimension==='2d'){const q=anchor?[clamp(anchor.q[0]+84*delta,1,99),anchor.q[1]]:[8+84*s.phase,32];if(validObserver(q,SCENES[s.map]))out.q2=q;}else out.qxy=anchor?[clamp(anchor.q[0]+77*delta,1,99),anchor.q[1]]:[8+77*s.phase,35];}return out;}
function captureSharedScene(s){const current=effectiveObserverState(s),family=sceneFamily(s);if(family==='plan'){sharedScenes.plan.map=current.map;sharedScenes.plan.observers[current.map]=[...current.q2];}else if(family==='terrain')for(const k of ['qxy','density','eye','ceiling'])sharedScenes.terrain[k]=structuredClone(current[k]);else sharedScenes.urban.light=[...current.light];}
function applySharedScene(s){const family=sceneFamily(s);if(family==='plan'){s.map=sharedScenes.plan.map;s.q2=[...sharedScenes.plan.observers[s.map]];}else if(family==='terrain')Object.assign(s,structuredClone(sharedScenes.terrain));else s.light=[...sharedScenes.urban.light];return s;}
function transitionSharedScene(previous,next,changedKey){captureSharedScene(previous);if(changedKey==='map'){sharedScenes.plan.map=next.map;next.q2=[...sharedScenes.plan.observers[next.map]];}else if(changedKey==='dimension'){applySharedScene(next);}else if(changedKey==='variant'&&previous.variant==='move'){const effective=effectiveObserverState(previous);next.q2=effective.q2;next.qxy=effective.qxy;}if(['map','dimension','variant'].includes(changedKey))anchorMovingObserver(next);captureSharedScene(next);return next;}
function stateWithSharedScene(previous,input){captureSharedScene(previous);let next=validate({...previous,...input});if(sceneFamily(next)!==sceneFamily(previous)||next.scene!==previous.scene||input.dimension!==undefined||input.map!==undefined){applySharedScene(next);if(input.map!==undefined){next.map=clamp(Math.round(Number(input.map)||0),0,SCENES.length-1);next.q2=[...sharedScenes.plan.observers[next.map]];}for(const k of ['q2','qxy','density','eye','ceiling','light'])if(Object.hasOwn(input,k))next[k]=structuredClone(input[k]);next=validate(next);}if(previous.scene!==next.scene||input.dimension!==undefined||input.map!==undefined||input.variant!==undefined||input.q2!==undefined||input.qxy!==undefined)anchorMovingObserver(next);captureSharedScene(next);return next;}
function restoreSharedScenes(saved){if(!saved||typeof saved!=='object')return;for(let map=0;map<SCENES.length;map++){const q=saved.plan?.observers?.[map];if(Array.isArray(q)&&q.length===2&&q.every(Number.isFinite)&&validObserver(q,SCENES[map]))sharedScenes.plan.observers[map]=[...q];}const p=validate({...DEFAULT,map:saved.plan?.map}),t=validate({...DEFAULT,...saved.terrain}),u=validate({...DEFAULT,...saved.urban});sharedScenes.plan.map=p.map;for(const k of ['qxy','density','eye','ceiling'])sharedScenes.terrain[k]=structuredClone(t[k]);sharedScenes.urban.light=[...u.light];}
