/* Terrain construction figures share a physical scene and a picked face.
 * The external camera is only for illustration. Detail cameras remain at q. */
function chooseBranch(e,q){const candidates=e.surfaces.filter(f=>f.kind==='terrain'&&area3(f.poly)>.15).sort((a,b)=>(centroid(b.poly)[0]-q[0])*Math.sqrt(area3(b.poly))-(centroid(a.poly)[0]-q[0])*Math.sqrt(area3(a.poly)));return pathTo(e.visits,candidates[0]?.visit??e.visits.length-1);}
function blockingFace(d){if(d.blocker!==undefined)return d.blocker;const q=d.q,tris=d.model.tris;let best=0,score=-1;for(let i=0;i<tris.length;i++){const c=centroid(tris[i]);if(c[0]<18||c[0]>43||Math.abs(c[1]-q[1])>22)continue;const h=shadowPlanes(tris[i],q);let a=0;for(const t of tris)a+=area3(t)-subtractShadow(t,h).reduce((sum,p)=>sum+area3(p),0);if(a>score){score=a;best=i;}}d.blocker=best;return best;}
function singleShadow(d,id){return memo('single'+d.model.tris.length+keyq(d.q)+id,()=>attachSolverWork(()=>{const tri=d.model.tris[id],h=shadowPlanes(tri,d.q),remain=[],blocked=[];d.model.tris.forEach((t,owner)=>{const off=subtractShadow(t,h);off.forEach(poly=>remain.push({poly,owner,kind:'terrain'}));if(h&&Math.max(...t.map(p=>val3(h[0],p)))>E3){const over=clipByPlanes(t,h);if(over.length>2)blocked.push({poly:over,owner,kind:'terrain'});}});return {remain,blocked,area:blocked.reduce((a,f)=>a+area3(f.poly),0)};}));}
function chooseProjection(d){const ref=getReference(d);let best=-1,score=-1;ref.pieces.forEach((f,i)=>{const t=d.model.tris[i],a=area3(t),v=f.polys.reduce((n,p)=>n+area3(p),0),c=centroid(t);if(v>a*.08&&v<a*.95&&c[0]>42){const scoreHere=a*(1-Math.abs(v/a-.5));if(scoreHere>score){score=scoreHere;best=i;}}});return best>=0?best:Math.max(0,d.model.tris.findIndex(t=>centroid(t)[0]>55));}
function targetFace(s,d,automatic=chooseProjection){return s.face<0?automatic(d):clamp(s.face,0,d.model.tris.length-1);}
function registerTerrain(s,d,cam,selectFaces=false){register(d.q,cam,'terrain');Object.assign(hitTargets[hitTargets.length-1],{triangles:d.model.tris,selectFaces});}
function terrainLayout(s){const g=G(s),side=Math.min(380,Math.max(280,g.w*.31)),gap=24;return {g,main:s.inset?{x:g.x,y:50,w:g.w-side-gap,h:800}:g,detail:{x:g.x+g.w-side,y:115,w:side,h:310},plan:{x:g.x+g.w-side,y:593,w:side,h:245}};}
function insetBox(rect,title=null){ctx.fillStyle='#fff';ctx.fillRect(rect.x-8,rect.y-(title?32:8),rect.w+16,rect.h+(title?40:16));if(title)text2(title,rect.x,rect.y-12,18,C.ink);}
let figureLabelBoxes=[];
function pointLabel(text,p,color,dx=7,dy=-8){
 const width=Math.max(22,text.length*14+6),height=30,candidates=[[dx,dy],[dx,dy+34],[dx,dy-34],[-width-7,dy],[-width-7,dy+34],[-width-7,dy-34]];
 // Several real clip intersections can be almost coincident in the outside
 // illustration. Search more label positions and connect displaced letters.
 for(const radius of [48,72,96,120])for(let i=0;i<8;i++){const a=i*Math.PI/4;candidates.push([Math.cos(a)*radius-width/2,Math.sin(a)*radius+height/2]);}
 for(const offset of candidates){const box={x:p[0]+offset[0],y:p[1]+offset[1]-height,w:width,h:height};if(!figureLabelBoxes.some(b=>box.x<b.x+b.w+3&&box.x+box.w+3>b.x&&box.y<b.y+b.h+3&&box.y+box.h+3>b.y)){[dx,dy]=offset;figureLabelBoxes.push(box);break;}}
 if(Math.hypot(dx,dy)>40)line2(p,[p[0]+dx+width/2,p[1]+dy-height/2],color,1,[2,3]);
 ctx.raw(`<text data-point-label="${escapeSVG(text)}" x="${svgNumber(p[0]+dx)}" y="${svgNumber(p[1]+dy)}" fill="${color}" stroke="#fff" stroke-width="4.5" stroke-linejoin="round" paint-order="stroke fill" font-family="Futura,Helvetica Neue,Helvetica,sans-serif" font-size="20" font-weight="600">${escapeSVG(text)}</text>`);
}
function focusProjector(q,points){let f=unit(sub(centroid(points),q));if(norm(f)<1e-7)f=[1,0,0];if(points.some(p=>dot(sub(p,q),f)<=.01)&&points.length>=3){let n=normal3(points);if(norm(n)>1e-7){if(dot(n,sub(centroid(points),q))<0)n=mul(n,-1);if(points.every(p=>dot(sub(p,q),n)>.01))f=n;}}return projector(q,f,Math.abs(f[2])>.98?[0,1,0]:[0,0,1]);}
function fittedFrame(points,pc,rect,padding=1.4,focus=centroid(points)){const projected=points.filter(p=>dot(sub(p,pc.q),pc.f)>.01).map(pc.point).filter(p=>p.every(Number.isFinite));if(!projected.length)return [[-1,-1],[1,-1],[1,1],[-1,1]];const box=bboxOf(projected,2),center=pc.point(focus),cx=Number.isFinite(center[0])?center[0]:(box.lo[0]+box.hi[0])/2,cy=Number.isFinite(center[1])?center[1]:(box.lo[1]+box.hi[1])/2,ratio=rect.w/rect.h,h=Math.max(.04,2*Math.max(cy-box.lo[1],box.hi[1]-cy)*padding,2*Math.max(cx-box.lo[0],box.hi[0]-cx)*padding/ratio),w=h*ratio;return [[cx-w/2,cy-h/2],[cx+w/2,cy-h/2],[cx+w/2,cy+h/2],[cx-w/2,cy+h/2]];}
function projectionFrame(target,pc,focus,rect={w:500,h:405}){return focus?fittedFrame(target,pc,rect,1.8):[[-1.45,-.72],[1.45,-.72],[1.45,1],[-1.45,1]];}
function insetClip(rect,id){ctx.raw(`<defs><clipPath id="${id}"><rect x="${svgNumber(rect.x)}" y="${svgNumber(rect.y)}" width="${svgNumber(rect.w)}" height="${svgNumber(rect.h)}"/></clipPath></defs><g clip-path="url(#${id})">`);}
function projectedContext(d,pc,frame,m,surfaces,color='#dce4e5'){for(const f of surfaces){const p=projectPolygon(f.poly,pc,frame);if(p.length>2)poly2(p.map(m.p),color,'#a3b2b6',.8);}}
function vertexLetters(i){let name='';for(i++;i>0;i=Math.floor((i-1)/26))name=String.fromCharCode(65+(i-1)%26)+name;return name;}
function constructionVertices(groups){const vertices=[];for(const [points,color] of groups)for(const p of points)if(!vertices.some(v=>norm(sub(v.p,p))<1e-6))vertices.push({p,color,label:vertexLetters(vertices.length)});return vertices;}
function drawConstructionLabels(s,vertices,project,which){if(!s.labels)return;ctx.raw(`<g data-terrain-vertices="${which}">`);for(const v of vertices){const p=project(v.p);if(!p||!p.every(Number.isFinite))continue;dot2(p,4,v.color);pointLabel(v.label,p,v.color);}ctx.raw('</g>');}
function projectedSegment(a,b,pc,frame){const da=dot(sub(a,pc.q),pc.f),db=dot(sub(b,pc.q),pc.f);if(da<=.01&&db<=.01)return null;if(da<.01)a=lerp(a,b,(.01-da)/(db-da));else if(db<.01)b=lerp(a,b,(.01-da)/(db-da));const box=bboxOf(frame,2);return clipSegment2([pc.point(a),pc.point(b)],[{n:[1,0],d:box.lo[0]},{n:[-1,0],d:-box.hi[0]},{n:[0,1],d:box.lo[1]},{n:[0,-1],d:-box.hi[1]}]);}
function projectedHighlights(faces,lines,pc,frame,m){const greenFaces=faces.filter(f=>[C.green,C.teal,C.tealLight].includes(f.color)),greenLines=lines.filter(l=>[C.green,C.teal,C.tealLight].includes(l.color));ctx.raw(`<g data-observer-highlights="true" data-face-count="${greenFaces.length}" data-edge-count="${greenLines.length}">`);for(const f of greenFaces){const p=projectPolygon(f.poly,pc,frame);if(p.length>2)poly2(p.map(m.p),rgba(f.color,f.alpha??.48));}for(const l of greenLines){const edge=projectedSegment(l.a,l.b,pc,frame);if(edge)line2(...edge.map(m.p),rgba(l.color,l.alpha??1),l.width??2.5);}ctx.raw('</g>');}
function beamDetailFrame(d,active,part,clipped,rect){const whole=active.whole||d.model.cells[active.cell].faces[0].poly,opening=active.aperture||whole,subject=part===0?whole:part===1?opening:[...new Map(clipped.flat().map(p=>[keyq(p),p])).values()],points=subject.length?subject:whole;let pc=focusProjector(d.q,points);if(whole.some(p=>dot(sub(p,d.q),pc.f)<=.01))pc=focusProjector(d.q,whole);const frame=fittedFrame([...whole,...points],pc,rect,1.4,centroid(points));return {whole,opening,points,pc,frame};}
function drawLinkedTerrainPlan(s,d,faces,lines,rect,selectFaces=false){
 if(!s.inset)return;insetBox(rect);const m=mapFit(rect,[[0,0],[100,0],[100,70],[0,70]]),top=camera3(rect,0,Math.PI/2,[50,35,12],Math.min(rect.w/100,rect.h/70));
 ctx.raw(`<g data-terrain-view="plan" data-face-count="${faces.length}" data-edge-count="${lines.length}">`);insetClip(rect,'terrain-plan-clip');drawWorld(top,faces,lines);ctx.raw('</g></g>');poly2([[0,0],[100,0],[100,70],[0,70]].map(m.p),null,C.wallLine,1.3);observer2(s.qxy,m,false);
 hitTargets.push({kind:'terrainPlan',m,rect,point:m.p(s.qxy),triangles:d.model.tris,selectFaces});
}
function drawBeamDetail(s,d,active,part,clipped,rect,faces,lines,vertices){
 if(!s.inset)return;const {whole,opening,points,pc,frame}=beamDetailFrame(d,active,part,clipped,rect),m=mapFit(rect,frame),label=['Whole shared face','Surviving opening','Clipped air cell'][part];
 hitTargets.push({kind:'terrainDetail',inset:true,rect,point:[-1e6,-1e6]});insetBox(rect,'Observer view · '+label.toLowerCase());ctx.raw(`<g data-terrain-view="detail" data-step="${part}" data-cell="${active.cell}" data-focus="${escapeSVG(keyq(centroid(points)))}">`);poly2(frame.map(m.p),'#f5f8f9',C.wallLine,1.5);insetClip(rect,'beam-detail-clip');projectedContext(d,pc,frame,m,terrainFaces(d.model));
 poly2(projectPolygon(whole,pc,frame).map(m.p),rgba(C.purple,.10));projectedHighlights(faces,lines,pc,frame,m);
 // These artificial shared faces are inspection overlays, not opaque terrain.
 // Keep the entire input face and opening above context and accumulated fills.
 ctx.raw('<g data-current-face-overlay="true">');poly2(projectPolygon(whole,pc,frame).map(m.p),null,C.purple,3);
 if(part>=1)poly2(projectPolygon(opening,pc,frame).map(m.p),rgba(C.orange,.25),C.orange,3.5);ctx.raw('</g>');
 drawConstructionLabels(s,vertices,p=>dot(sub(p,d.q),pc.f)>.01?m.p(pc.point(p)):null,'observer');ctx.raw('</g></g>');
 text2('Input face shown above the terrain.',rect.x,rect.y+rect.h+27,17,C.muted);
}
function airWireLines(s,d){if(!s.airWire)return [];if(!d.airEdges)d.airEdges=uniqueEdges(d.model.cells.flatMap(c=>c.faces.map(f=>f.poly)));return segLines(d.airEdges,'#899ba5',1.2,s.airOpacity);}
function drawTerrainMain(cam,faces,lines){ctx.raw(`<g data-terrain-view="main" data-face-count="${faces.length}" data-edge-count="${lines.length}">`);drawWorld(cam,faces,lines);ctx.raw('</g>');}
function drawAir(s){
 figureLabelBoxes=[];
 if(s.variant==='project'){drawBeamTargetCut(s);return;}
 const d=terrainState(s),e=getBeams(d),q=d.q,layout=terrainLayout(s),cam=cameraMain(s,layout.main,[50,35,d.model.roof*.36]),branch=chooseBranch(e,q),faces=terrainFaces(d.model),lines=[...(s.wire?groundLines(d.model):[]),...airWireLines(s,d)];let idx=0,part=0,shown=[],historyIDs=[];
 if(s.variant==='branch'){stepCount=Math.max(1,(branch.length-1)*3);const k=Math.min(stepCount-1,Math.floor(s.phase*stepCount));idx=branch[Math.min(branch.length-1,1+Math.floor(k/3))];part=k%3;historyIDs=branch.slice(0,1+Math.floor(k/3));const seen=new Set(historyIDs.concat(part===2?[idx]:[]));shown=e.surfaces.filter(f=>seen.has(f.visit));}
 else{stepCount=e.visits.length;idx=Math.min(e.visits.length-1,Math.floor(s.phase*e.visits.length));part=2;shown=e.surfaces.filter(f=>f.visit<=idx);}
 const active=e.visits[idx],cell=d.model.cells[active.cell],clipped=clipCell(cell,active.beam);
 faces.push(...surfaceFaces(shown.filter(f=>f.kind==='terrain'),C.green));lines.push(...completedLines(s,shown.filter(f=>f.kind==='terrain'),d.model));
 cell.faces.forEach(f=>{faces.push({poly:f.poly,color:C.purple,alpha:.035,shade:false});lines.push(...edges3(f.poly,C.purple,.52));});
 if(s.history&&s.variant==='branch')for(const id of historyIDs.slice(1)){const v=e.visits[id],polys=clipCell(d.model.cells[v.cell],v.beam);lines.push(...segLines(uniqueEdges(polys),C.teal,1.5,.42));}
 if(active.aperture){faces.push({poly:active.whole,color:C.purple,alpha:.09,shade:false});lines.push(...segLines(uniqueEdges([active.whole]),C.purple,3));if(part>=1){faces.push({poly:active.aperture,color:C.orange,alpha:.25,shade:false});lines.push(...segLines(uniqueEdges([active.aperture]),C.orange,3.5));if(part===2)faces.push(...clipped.map(poly=>({poly,color:C.green,alpha:.22,shade:false})));lines.push(...segLines(uniqueEdges(clipped),C.teal,part===2?3:2.5));for(const p of active.aperture){lines.push({a:q,b:p,color:C.orange,alpha:.75,width:2});const dir=sub(p,q),eligible=clipped.flat().filter(v=>norm(cross3(sub(v,q),dir))/norm(dir)<1e-5),far=eligible.sort((a,b)=>norm(sub(b,q))-norm(sub(a,q)))[0];if(far)lines.push({a:p,b:far,color:C.teal,width:3});}}}
 const whole=active.whole||cell.faces[0].poly,vertices=constructionVertices([[whole,C.purple],[part>=1?(active.aperture||whole):[],C.orange]]);
 drawTerrainMain(cam,faces,lines);ink3(whole,cam,C.purple,2.5);if(active.aperture&&part>=1)ink3(active.aperture,cam,C.orange,4);observer3(q,cam,q[2]-s.eye,s.labels);drawConstructionLabels(s,vertices,cam.p,'main');registerTerrain(s,d,cam);
 drawBeamDetail(s,d,active,part,clipped,layout.detail,faces,lines,vertices);drawLinkedTerrainPlan(s,d,faces,lines,layout.plan);
 setPanel({title:s.variant==='expand'?'Accumulate the beam branches':['A shared face between air cells','Clip the face and extend the beam','Keep the cut part of the next cell'][part],steps:s.variant==='branch'?['Whole triangular face','Surviving polygonal opening','Clipped air cell → terrain']:null,active:part,body:[s.variant==='expand'?'Every shared face transmits only the remaining straight-line beam. A terrain face stops the branch and records a visible polygon.':['Purple marks an artificial air-cell boundary. The observer inset looks directly at this face from q.','Orange is the surviving opening. Its boundary directions cut the next air cell; both insets show those same edges.','The teal boundary encloses the remaining cell. Earlier terrain cuts stay visible as the beam continues.'][part]],stats:[['Terrain / air tetrahedra',`${d.model.tris.length} / ${d.model.cells.length}`],['Beam entries',s.variant==='branch'?`${branch.indexOf(idx)+1} / ${branch.length} on this path`:`${idx+1} / ${e.visits.length}`],['Ceiling elevation',number(d.model.roof,1)+' m'],['Highest terrain / observer',`${number(d.model.peak,1)} / ${number(q[2],1)} m`]],legend:[[C.purple,'Whole face / input cell'],[C.orange,'Clipped opening'],[C.teal,'Beam cut edges'],[C.green,'Visible terrain found']],note:'Scroll the main view to zoom. The observer inset stays centered on the current construction.',progress:{kind:'beams',index:idx+1,part,...(s.variant==='branch'?{ids:[...historyIDs,idx]}:{})}});
}
function drawTerrain(s){return s.variant==='one'?drawTerrainSingleShadow(s):drawTerrainSubtraction(s);}
function beamTarget(d,id){const e=getBeams(d),fragments=e.surfaces.filter(f=>f.kind==='terrain'&&d.model.boundary[f.boundary].terrainID===id),ids=[...new Set(fragments.flatMap(f=>pathTo(e.visits,f.visit)))].sort((a,b)=>a-b);return {e,fragments,ids,visible:fragments.map(f=>f.poly)};}
function targetCutEdges(visible,target){return receiverCutEdges(visible,target);}
function limitingObstruction(d,id,p,target){let hit=firstFast(d.q,sub(p,d.q),d.base.prepared,true);if(hit.id===id||hit.r>=1-1e-6)for(const vertex of target){const probe=firstFast(d.q,sub(lerp(p,vertex,.001),d.q),d.base.prepared,true);if(probe.id>=0&&probe.id!==id&&probe.r<1-1e-6){hit=probe;break;}}let near=p;if(hit.id>=0&&hit.id!==id){const h=planeOf(d.model.tris[hit.id]),dir=sub(p,d.q),den=dot(h.n,dir),t=(h.d-dot(h.n,d.q))/den;if(Number.isFinite(t)&&t>0&&t<=1+1e-4)near=add(d.q,mul(dir,t));else near=add(d.q,mul(dir,Math.min(hit.r,1)));}return {near,id:hit.id};}
function drawCutConstruction(d,id,visible,part,faces,lines){
 const q=d.q,target=d.model.tris[id],cuts=targetCutEdges(visible,target),blockers=[];
 if(part>=1)target.forEach(p=>lines.push({a:q,b:p,color:C.orange,alpha:.65,width:1.8}));
 if(part>=2){faces.push(...visible.map(poly=>({poly,color:C.green,bias:.0002})));for(const cut of cuts){for(const p of cut){const h=limitingObstruction(d,id,p,target);lines.push({a:q,b:h.near,color:C.purple,width:3},{a:h.near,b:p,color:C.teal,width:3});if(h.id>=0&&h.id!==id)blockers.push(h.id);}lines.push(...segLines([cut],C.teal,4));}if(!visible.length){const p=centroid(target),h=firstFast(q,sub(p,q),d.base.prepared,true);if(h.id>=0&&h.id!==id){blockers.push(h.id);lines.push({a:q,b:add(q,mul(sub(p,q),h.r)),color:C.purple,width:3});}}for(const b of new Set(blockers)){faces.push({poly:d.model.tris[b],color:C.purple,alpha:.28,bias:.0002});lines.push(...segLines(uniqueEdges([d.model.tris[b]]),C.purple,2.5));}}
 return cuts;
}
function drawTargetObserver(s,d,target,visible,cuts,part,rect,pc,frame,background,complete=false,vertices=[],linked=null){
 const m=mapFit(rect,frame);hitTargets.push({kind:'terrainDetail',inset:true,rect,point:[-1e6,-1e6]});insetBox(rect,complete?'Observer view · forward +X':'Observer view · target detail');ctx.raw(`<g data-terrain-view="detail" data-step="${part}" data-face="${targetFace(s,d)}">`);poly2(frame.map(m.p),'#f2f6f8',C.wallLine,2);insetClip(rect,'target-detail-clip');projectedContext(d,pc,frame,m,background,complete?C.tealLight:'#dce4e5');
 if(linked)projectedHighlights(linked.faces,linked.lines,pc,frame,m);
 if(!complete){const raw=projectPolygon(target,pc,frame);poly2(raw.map(m.p),part<2?rgba(C.orange,.26):null);if(part>=2){visible.forEach(p=>poly2(projectPolygon(p,pc,frame).map(m.p),C.tealLight,C.teal,3));cuts.forEach(([a,b])=>line2(m.p(pc.point(a)),m.p(pc.point(b)),C.purple,4));}
 ctx.raw('<g data-current-face-overlay="true">');poly2(raw.map(m.p),null,C.orange,3,part<2?[]:[7,5]);ctx.raw('</g>');drawConstructionLabels(s,vertices,p=>dot(sub(p,d.q),pc.f)>.01?m.p(pc.point(p)):null,'observer');}
 ctx.raw('</g></g>');return m;
}
function drawBeamTargetCut(s){
 figureLabelBoxes=[];
 const d=terrainState(s),q=d.q,id=targetFace(s,d),target=d.model.tris[id],beam=beamTarget(d,id),visible=beam.visible,part=Math.min(3,Math.floor(s.phase*4)),layout=terrainLayout(s),cam=cameraMain(s,layout.main,[50,35,12]),pc=focusProjector(q,target),frame=projectionFrame(target,pc,true,layout.detail),faces=terrainFaces(d.model),lines=[...(s.wire?groundLines(d.model):[]),...airWireLines(s,d)];stepCount=4;
 faces.push({poly:target,color:C.orange,bias:.0001});
 const cuts=drawCutConstruction(d,id,visible,part,faces,lines);
 if(part>=1)for(const visit of beam.ids){const v=beam.e.visits[visit];if(v.aperture&&visit===beam.ids.at(-1)){lines.push(...segLines(uniqueEdges([v.whole]),C.purple,2.5,.55),...segLines(uniqueEdges([v.aperture]),C.orange,3));if(part>=2)lines.push(...segLines(uniqueEdges(clipCell(d.model.cells[v.cell],v.beam)),C.teal,2,.65));}}
 const vertices=constructionVertices([[target,C.orange],[part>=2?cuts.flat():[],C.purple]]);
 drawTerrainMain(cam,faces,lines);observer3(q,cam,q[2]-s.eye,s.labels);registerTerrain(s,d,cam,true);ink3(target,cam,C.orange,2.5);if(part>=2)visible.forEach(p=>ink3(p,cam,C.teal,3));drawConstructionLabels(s,vertices,cam.p,'main');
 if(s.inset)drawTargetObserver(s,d,target,visible,cuts,part,layout.detail,pc,frame,terrainFaces(d.model),false,vertices,{faces,lines});
 drawLinkedTerrainPlan(s,d,faces,lines,layout.plan,true);
 const visibleArea=visible.reduce((a,p)=>a+area3(p),0),partial=visibleArea>1e-7&&visibleArea<area3(target)-1e-7;
 setPanel({title:['Select a terrain triangle','Follow its boundary directions','Find where the terrain cuts it','Keep the surviving physical face'][part],steps:['Whole terrain face','Trace its beam directions','Retain the cut face'],active:Math.min(2,part),body:[['Click any terrain triangle in the main view or plan. The inset looks directly toward the selected face.','Orange lines connect q to the original face. The beam detail shares the same scene and plan.',partial?'Purple directions reach the nearer obstruction; teal continuations reach the cut vertices.':visibleArea<1e-7?'This selected face is fully hidden. No beam reaches its physical surface.':'This selected face is fully visible. Its boundary survives without an interior cut.','The surviving inset footprint returns to the same physical surface.'][part]],stats:[['Target triangle',String(id)],['Original sloping triangle',number(area3(target))+' m²'],['Its visible portion',part>=2?number(visibleArea)+' m²':'—']],legend:[[C.orange,'Original face / boundary directions'],[C.purple,'Occluding face / limiting directions'],[C.teal,'Geometric cut edge'],[C.tealLight,'Surviving surface fragment']],note:'Click selects a face; drag rotates the illustration; scroll zooms the main view.',progress:{kind:'beams',ids:part>=1?beam.ids:[],index:part>=1?(beam.ids.at(-1)??-1)+1:0,part}});
}
